<a href="https://colab.research.google.com/github/Yachika08/Pyspark_practice/blob/pyspark_assignments/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!apt-get update
!apt-get install openjdk-8-jdk-headless -qq > /dev/null
!wget -q https://dlcdn.apache.org/spark/spark-3.3.2/spark-3.3.2-bin-hadoop3.tgz
!tar zxvf spark-3.3.2-bin-hadoop3.tgz
!pip install -q findspark

import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.3.2-bin-hadoop3"

!pip install pyspark==3.2.1
!pip install --upgrade findspark

import pyspark

Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:4 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease [3,622 B]
Get:5 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease [18.1 kB]
Hit:6 http://ppa.launchpad.net/cran/libgit2/ubuntu focal InRelease
Hit:7 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Get:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease [1,581 B]
Get:10 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease [24.3 kB]
Hit:11 http://ppa.launchpad.net/ubuntugis/ppa/ubuntu focal InRelease
Get:12 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ Packages [81.0 kB]
Get:13 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal/main Sources [2,604 kB]
Get:14 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal/main amd64 Packages [1,229 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [2,636 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [39.5 kB]
Get:17 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  Packages [1,079 kB]
Get:18 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal/main amd64 Packages [44.1 kB]
Fetched 8,096 kB in 2s (3,273 kB/s)
Reading package lists... Done
spark-3.3.2-bin-hadoop3/
spark-3.3.2-bin-hadoop3/LICENSE
spark-3.3.2-bin-hadoop3/NOTICE
spark-3.3.2-bin-hadoop3/R/
spark-3.3.2-bin-hadoop3/R/lib/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/DESCRIPTION
spark-3.3.2-bin-hadoop3/R/lib/SparkR/INDEX
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/Rd.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/features.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/hsearch.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/links.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/nsInfo.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/package.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/Meta/vignette.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/NAMESPACE
spark-3.3.2-bin-hadoop3/R/lib/SparkR/R/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/R/SparkR
spark-3.3.2-bin-hadoop3/R/lib/SparkR/R/SparkR.rdb
spark-3.3.2-bin-hadoop3/R/lib/SparkR/R/SparkR.rdx
spark-3.3.2-bin-hadoop3/R/lib/SparkR/doc/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/doc/index.html
spark-3.3.2-bin-hadoop3/R/lib/SparkR/doc/sparkr-vignettes.R
spark-3.3.2-bin-hadoop3/R/lib/SparkR/doc/sparkr-vignettes.Rmd
spark-3.3.2-bin-hadoop3/R/lib/SparkR/doc/sparkr-vignettes.html
spark-3.3.2-bin-hadoop3/R/lib/SparkR/help/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/help/AnIndex
spark-3.3.2-bin-hadoop3/R/lib/SparkR/help/SparkR.rdb
spark-3.3.2-bin-hadoop3/R/lib/SparkR/help/SparkR.rdx
spark-3.3.2-bin-hadoop3/R/lib/SparkR/help/aliases.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/help/paths.rds
spark-3.3.2-bin-hadoop3/R/lib/SparkR/html/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/html/00Index.html
spark-3.3.2-bin-hadoop3/R/lib/SparkR/html/R.css
spark-3.3.2-bin-hadoop3/R/lib/SparkR/profile/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/profile/general.R
spark-3.3.2-bin-hadoop3/R/lib/SparkR/profile/shell.R
spark-3.3.2-bin-hadoop3/R/lib/SparkR/tests/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/tests/testthat/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/tests/testthat/test_basic.R
spark-3.3.2-bin-hadoop3/R/lib/SparkR/worker/
spark-3.3.2-bin-hadoop3/R/lib/SparkR/worker/daemon.R
spark-3.3.2-bin-hadoop3/R/lib/SparkR/worker/worker.R
spark-3.3.2-bin-hadoop3/R/lib/sparkr.zip
spark-3.3.2-bin-hadoop3/README.md
spark-3.3.2-bin-hadoop3/RELEASE
spark-3.3.2-bin-hadoop3/bin/
spark-3.3.2-bin-hadoop3/bin/beeline
spark-3.3.2-bin-hadoop3/bin/beeline.cmd
spark-3.3.2-bin-hadoop3/bin/docker-image-tool.sh
spark-3.3.2-bin-hadoop3/bin/find-spark-home
spark-3.3.2-bin-hadoop3/bin/find-spark-home.cmd
spark-3.3.2-bin-hadoop3/bin/load-spark-env.cmd
spark-3.3.2-bin-hadoop3/bin/load-spark-env.sh
spark-3.3.2-bin-hadoop3/bin/pyspark
spark-3.3.2-bin-hadoop3/bin/pyspark.cmd
spark-3.3.2-bin-hadoop3/bin/pyspark2.cmd
spark-3.3.2-bin-hadoop3/bin/run-example
spark-3.3.2-bin-hadoop3/bin/run-example.cmd
spark-3.3.2-bin-hadoop3/bin/spark-class
spark-3.3.2-bin-hadoop3/bin/spark-class.cmd
spark-3.3.2-bin-hadoop3/bin/spark-class2.cmd
spark-3.3.2-bin-hadoop3/bin/spark-shell
spark-3.3.2-bin-hadoop3/bin/spark-shell.cmd
spark-3.3.2-bin-hadoop3/bin/spark-shell2.cmd
spark-3.3.2-bin-hadoop3/bin/spark-sql
spark-3.3.2-bin-hadoop3/bin/spark-sql.cmd
spark-3.3.2-bin-hadoop3/bin/spark-sql2.cmd
spark-3.3.2-bin-hadoop3/bin/spark-submit
spark-3.3.2-bin-hadoop3/bin/spark-submit.cmd
spark-3.3.2-bin-hadoop3/bin/spark-submit2.cmd
spark-3.3.2-bin-hadoop3/bin/sparkR
spark-3.3.2-bin-hadoop3/bin/sparkR.cmd
spark-3.3.2-bin-hadoop3/bin/sparkR2.cmd
spark-3.3.2-bin-hadoop3/conf/
spark-3.3.2-bin-hadoop3/conf/fairscheduler.xml.template
spark-3.3.2-bin-hadoop3/conf/log4j2.properties.template
spark-3.3.2-bin-hadoop3/conf/metrics.properties.template
spark-3.3.2-bin-hadoop3/conf/spark-defaults.conf.template
spark-3.3.2-bin-hadoop3/conf/spark-env.sh.template
spark-3.3.2-bin-hadoop3/conf/workers.template
spark-3.3.2-bin-hadoop3/data/
spark-3.3.2-bin-hadoop3/data/graphx/
spark-3.3.2-bin-hadoop3/data/graphx/followers.txt
spark-3.3.2-bin-hadoop3/data/graphx/users.txt
spark-3.3.2-bin-hadoop3/data/mllib/
spark-3.3.2-bin-hadoop3/data/mllib/als/
spark-3.3.2-bin-hadoop3/data/mllib/als/sample_movielens_ratings.txt
spark-3.3.2-bin-hadoop3/data/mllib/als/test.data
spark-3.3.2-bin-hadoop3/data/mllib/gmm_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/images/
spark-3.3.2-bin-hadoop3/data/mllib/images/license.txt
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/kittens/
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/kittens/29.5.a_b_EGDP022204.jpg
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/kittens/54893.jpg
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/kittens/DP153539.jpg
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/kittens/DP802813.jpg
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/kittens/not-image.txt
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/license.txt
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/multi-channel/
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/multi-channel/BGRA.png
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/multi-channel/BGRA_alpha_60.png
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/multi-channel/chr30.4.184.jpg
spark-3.3.2-bin-hadoop3/data/mllib/images/origin/multi-channel/grayscale.jpg
spark-3.3.2-bin-hadoop3/data/mllib/kmeans_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/pagerank_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/pic_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/ridge-data/
spark-3.3.2-bin-hadoop3/data/mllib/ridge-data/lpsa.data
spark-3.3.2-bin-hadoop3/data/mllib/sample_binary_classification_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_fpgrowth.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_isotonic_regression_libsvm_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_kmeans_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_lda_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_lda_libsvm_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_libsvm_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_linear_regression_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_movielens_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_multiclass_classification_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/sample_svm_data.txt
spark-3.3.2-bin-hadoop3/data/mllib/streaming_kmeans_data_test.txt
spark-3.3.2-bin-hadoop3/data/streaming/
spark-3.3.2-bin-hadoop3/data/streaming/AFINN-111.txt
spark-3.3.2-bin-hadoop3/examples/
spark-3.3.2-bin-hadoop3/examples/jars/
spark-3.3.2-bin-hadoop3/examples/jars/scopt_2.12-3.7.1.jar
spark-3.3.2-bin-hadoop3/examples/jars/spark-examples_2.12-3.3.2.jar
spark-3.3.2-bin-hadoop3/examples/src/
spark-3.3.2-bin-hadoop3/examples/src/main/
spark-3.3.2-bin-hadoop3/examples/src/main/java/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaHdfsLR.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaLogQuery.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaPageRank.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaSparkPi.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaStatusTrackerDemo.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaTC.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/JavaWordCount.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaAFTSurvivalRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaALSExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaBinarizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaBisectingKMeansExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketedRandomProjectionLSHExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaBucketizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSqSelectorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaChiSquareTestExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaCorrelationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaCountVectorizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaDCTExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeClassificationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaDecisionTreeRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaDocument.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaElementwiseProductExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaEstimatorTransformerParamExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaFMClassifierExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaFMRegressorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaFPGrowthExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaFeatureHasherExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaGaussianMixtureExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaGeneralizedLinearRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeClassifierExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaGradientBoostedTreeRegressorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaImputerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaIndexToStringExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaInteractionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaIsotonicRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaKMeansExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLDAExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLabeledDocument.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearRegressionWithElasticNetExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLinearSVCExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionSummaryExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaLogisticRegressionWithElasticNetExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMaxAbsScalerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMinHashLSHExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMinMaxScalerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaCrossValidationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaModelSelectionViaTrainValidationSplitExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMulticlassLogisticRegressionWithElasticNetExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaMultilayerPerceptronClassifierExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaNGramExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaNaiveBayesExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaNormalizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaOneHotEncoderExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaOneVsRestExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPCAExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPipelineExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPolynomialExpansionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPowerIterationClusteringExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaPrefixSpanExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaQuantileDiscretizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaRFormulaExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestClassifierExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaRandomForestRegressorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaRobustScalerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaSQLTransformerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaStandardScalerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaStopWordsRemoverExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaStringIndexerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaSummarizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaTfIdfExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaTokenizerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaUnivariateFeatureSelectorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVarianceThresholdSelectorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorAssemblerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorIndexerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSizeHintExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaVectorSlicerExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/ml/JavaWord2VecExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaALS.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaAssociationRulesExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaBinaryClassificationMetricsExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaBisectingKMeansExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaChiSqSelectorExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaCorrelationsExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeClassificationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaDecisionTreeRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaElementwiseProductExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaGaussianMixtureExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingClassificationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaGradientBoostingRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaHypothesisTestingKolmogorovSmirnovTestExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaIsotonicRegressionExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaKMeansExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaKernelDensityEstimationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaLBFGSExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaLatentDirichletAllocationExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaLogisticRegressionWithLBFGSExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaMultiLabelClassificationMetricsExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaMulticlassClassificationMetricsExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaNaiveBayesExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaPCAExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaPowerIterationClusteringExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaPrefixSpanExample.java
spark-3.3.2-bin-hadoop3/examples/src/main/java/org/apache/spark/examples/mllib/JavaRandomForestClassificationExample.java

In [ ]:
from pyspark.sql import SparkSession

# Create a SparkSession
spark = SparkSession.builder \
    .appName("YourAppName") \
    .master("local[*]") \
    .getOrCreate()

In [ ]:
spark

In [ ]:
house_df= spark.read.csv("/content/sample_data/california_housing_test.csv", header=True, inferSchema=True)

In [ ]:
house_df.show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|  -122.05|   37.37|              27.0|     3885.0|         661.0|    1537.0|     606.0|       6.6085|          344700.0|
|   -118.3|   34.26|              43.0|     1510.0|         310.0|     809.0|     277.0|        3.599|          176500.0|
|  -117.81|   33.78|              27.0|     3589.0|         507.0|    1484.0|     495.0|       5.7934|          270500.0|
|  -118.36|   33.82|              28.0|       67.0|          15.0|      49.0|      11.0|       6.1359|          330000.0|
|  -119.67|   36.33|              19.0|     1241.0|         244.0|     850.0|     237.0|       2.9375|           81700.0|
|  -119.56|   36.51|              37.0|     1018.0|         213.0|     663.0|     204.0|       1.6635|           67000.0|
|  -121.43|   38.63|              43.0|     1009.0|         225.0|     604.0|     218.0|       1.6641|           67000.0|
|  -120.65|   35.48|              19.0|     2310.0|         471.0|    1341.0|     441.0|        3.225|          166900.0|
|  -122.84|    38.4|              15.0|     3080.0|         617.0|    1446.0|     599.0|       3.6696|          194400.0|
|  -118.02|   34.08|              31.0|     2402.0|         632.0|    2830.0|     603.0|       2.3333|          164200.0|
|  -118.24|   33.98|              45.0|      972.0|         249.0|    1288.0|     261.0|       2.2054|          125000.0|
|  -119.12|   35.85|              37.0|      736.0|         166.0|     564.0|     138.0|       2.4167|           58300.0|
|  -121.93|   37.25|              36.0|     1089.0|         182.0|     535.0|     170.0|         4.69|          252600.0|
|  -117.03|   32.97|              16.0|     3936.0|         694.0|    1935.0|     659.0|       4.5625|          231200.0|
|  -117.97|   33.73|              27.0|     2097.0|         325.0|    1217.0|     331.0|       5.7121|          222500.0|
|  -117.99|   33.81|              42.0|      161.0|          40.0|     157.0|      50.0|          2.2|          153100.0|
|  -120.81|   37.53|              15.0|      570.0|         123.0|     189.0|     107.0|        1.875|          181300.0|
|   -121.2|   38.69|              26.0|     3077.0|         607.0|    1603.0|     595.0|       2.7174|          137500.0|
|  -118.88|   34.21|              26.0|     1590.0|         196.0|     654.0|     199.0|       6.5851|          300000.0|
|  -122.59|   38.01|              35.0|     8814.0|        1307.0|    3450.0|    1258.0|       6.1724|          414300.0|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
only showing top 20 rows

In [ ]:
from pyspark.sql.functions import col
house_df= house_df.withColumn("Total Income",col("population") * col("median_income"))

In [ ]:
house_df.count()

3000

In [ ]:
count = house_df.count()
print(" Number of records" ,house_df.count())

 Number of records 3000

In [ ]:
# print the columns of the table
columns = house_df.columns
print("Columns",columns)

Columns ['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'Total Income']

In [ ]:
##to show the column and datatypes of the columns
house_df.printSchema()

root
 |-- longitude: double (nullable = true)
 |-- latitude: double (nullable = true)
 |-- housing_median_age: double (nullable = true)
 |-- total_rooms: double (nullable = true)
 |-- total_bedrooms: double (nullable = true)
 |-- population: double (nullable = true)
 |-- households: double (nullable = true)
 |-- median_income: double (nullable = true)
 |-- median_house_value: double (nullable = true)
 |-- Total Income: double (nullable = true)

In [ ]:
#Drop Column
house_df = house_df.drop("median_income")
house_df.show()

+---------+--------+------------------+-----------+--------------+----------+----------+------------------+------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_house_value|      Total Income|
+---------+--------+------------------+-----------+--------------+----------+----------+------------------+------------------+
|  -122.05|   37.37|              27.0|     3885.0|         661.0|    1537.0|     606.0|          344700.0|10157.264500000001|
|   -118.3|   34.26|              43.0|     1510.0|         310.0|     809.0|     277.0|          176500.0|2911.5910000000003|
|  -117.81|   33.78|              27.0|     3589.0|         507.0|    1484.0|     495.0|          270500.0|         8597.4056|
|  -118.36|   33.82|              28.0|       67.0|          15.0|      49.0|      11.0|          330000.0|          300.6591|
|  -119.67|   36.33|              19.0|     1241.0|         244.0|     850.0|     237.0|           81700.0|          2496.875|
|  -119.56|   36.51|              37.0|     1018.0|         213.0|     663.0|     204.0|           67000.0|         1102.9005|
|  -121.43|   38.63|              43.0|     1009.0|         225.0|     604.0|     218.0|           67000.0|         1005.1164|
|  -120.65|   35.48|              19.0|     2310.0|         471.0|    1341.0|     441.0|          166900.0|          4324.725|
|  -122.84|    38.4|              15.0|     3080.0|         617.0|    1446.0|     599.0|          194400.0|         5306.2416|
|  -118.02|   34.08|              31.0|     2402.0|         632.0|    2830.0|     603.0|          164200.0|          6603.239|
|  -118.24|   33.98|              45.0|      972.0|         249.0|    1288.0|     261.0|          125000.0|2840.5552000000002|
|  -119.12|   35.85|              37.0|      736.0|         166.0|     564.0|     138.0|           58300.0|         1363.0188|
|  -121.93|   37.25|              36.0|     1089.0|         182.0|     535.0|     170.0|          252600.0|           2509.15|
|  -117.03|   32.97|              16.0|     3936.0|         694.0|    1935.0|     659.0|          231200.0|         8828.4375|
|  -117.97|   33.73|              27.0|     2097.0|         325.0|    1217.0|     331.0|          222500.0|6951.6257000000005|
|  -117.99|   33.81|              42.0|      161.0|          40.0|     157.0|      50.0|          153100.0|345.40000000000003|
|  -120.81|   37.53|              15.0|      570.0|         123.0|     189.0|     107.0|          181300.0|           354.375|
|   -121.2|   38.69|              26.0|     3077.0|         607.0|    1603.0|     595.0|          137500.0|         4355.9922|
|  -118.88|   34.21|              26.0|     1590.0|         196.0|     654.0|     199.0|          300000.0|         4306.6554|
|  -122.59|   38.01|              35.0|     8814.0|        1307.0|    3450.0|    1258.0|          414300.0|          21294.78|
+---------+--------+------------------+-----------+--------------+----------+----------+------------------+------------------+
only showing top 20 rows

In [ ]:
house_df = house_df.select("total_bedrooms")
house_df.show()

+--------------+
|total_bedrooms|
+--------------+
|         661.0|
|         310.0|
|         507.0|
|          15.0|
|         244.0|
|         213.0|
|         225.0|
|         471.0|
|         617.0|
|         632.0|
|         249.0|
|         166.0|
|         182.0|
|         694.0|
|         325.0|
|          40.0|
|         123.0|
|         607.0|
|         196.0|
|        1307.0|
+--------------+
only showing top 20 rows

In [ ]:
columns = house_df.columns
print("Columns",columns)

Columns ['total_bedrooms']

In [ ]:
# Filtering rooms greater than 2500
filter_df = house_df.filter(house_df["total_bedrooms"]>2550)
filter_df.show()

+--------------+
|total_bedrooms|
+--------------+
|        2971.0|
|        4522.0|
|        3493.0|
|        3173.0|
|        5027.0|
|        4135.0|
|        2616.0|
|        5419.0|
|        4055.0|
|        2552.0|
|        2696.0|
|        4585.0|
|        5033.0|
|        2727.0|
+--------------+

In [ ]:
# iterate the rows of the column in data
collected_data = house_df.collect()
for row in collected_data:
  print(row)

Row(total_bedrooms=661.0)
Row(total_bedrooms=310.0)
Row(total_bedrooms=507.0)
Row(total_bedrooms=15.0)
Row(total_bedrooms=244.0)
Row(total_bedrooms=213.0)
Row(total_bedrooms=225.0)
Row(total_bedrooms=471.0)
Row(total_bedrooms=617.0)
Row(total_bedrooms=632.0)
Row(total_bedrooms=249.0)
Row(total_bedrooms=166.0)
Row(total_bedrooms=182.0)
Row(total_bedrooms=694.0)
Row(total_bedrooms=325.0)
Row(total_bedrooms=40.0)
Row(total_bedrooms=123.0)
Row(total_bedrooms=607.0)
Row(total_bedrooms=196.0)
Row(total_bedrooms=1307.0)
Row(total_bedrooms=256.0)
Row(total_bedrooms=296.0)
Row(total_bedrooms=543.0)
Row(total_bedrooms=528.0)
Row(total_bedrooms=1040.0)
Row(total_bedrooms=218.0)
Row(total_bedrooms=1030.0)
Row(total_bedrooms=418.0)
Row(total_bedrooms=1609.0)
Row(total_bedrooms=954.0)
Row(total_bedrooms=220.0)
Row(total_bedrooms=493.0)
Row(total_bedrooms=705.0)
Row(total_bedrooms=2971.0)
Row(total_bedrooms=170.0)
Row(total_bedrooms=726.0)
Row(total_bedrooms=451.0)
Row(total_bedrooms=251.0)
Row(total_bedrooms=203.0)
Row(total_bedrooms=1035.0)
Row(total_bedrooms=275.0)
Row(total_bedrooms=406.0)
Row(total_bedrooms=226.0)
Row(total_bedrooms=186.0)
Row(total_bedrooms=286.0)
Row(total_bedrooms=1874.0)
Row(total_bedrooms=251.0)
Row(total_bedrooms=338.0)
Row(total_bedrooms=369.0)
Row(total_bedrooms=1698.0)
Row(total_bedrooms=1887.0)
Row(total_bedrooms=121.0)
Row(total_bedrooms=500.0)
Row(total_bedrooms=380.0)
Row(total_bedrooms=333.0)
Row(total_bedrooms=233.0)
Row(total_bedrooms=528.0)
Row(total_bedrooms=468.0)
Row(total_bedrooms=291.0)
Row(total_bedrooms=600.0)
Row(total_bedrooms=140.0)
Row(total_bedrooms=317.0)
Row(total_bedrooms=305.0)
Row(total_bedrooms=299.0)
Row(total_bedrooms=399.0)
Row(total_bedrooms=768.0)
Row(total_bedrooms=1212.0)
Row(total_bedrooms=319.0)
Row(total_bedrooms=750.0)
Row(total_bedrooms=367.0)
Row(total_bedrooms=382.0)
Row(total_bedrooms=544.0)
Row(total_bedrooms=442.0)
Row(total_bedrooms=419.0)
Row(total_bedrooms=291.0)
Row(total_bedrooms=225.0)
Row(total_bedrooms=631.0)
Row(total_bedrooms=694.0)
Row(total_bedrooms=858.0)
Row(total_bedrooms=1002.0)
Row(total_bedrooms=130.0)
Row(total_bedrooms=384.0)
Row(total_bedrooms=324.0)
Row(total_bedrooms=1416.0)
Row(total_bedrooms=509.0)
Row(total_bedrooms=560.0)
Row(total_bedrooms=190.0)
Row(total_bedrooms=631.0)
Row(total_bedrooms=345.0)
Row(total_bedrooms=362.0)
Row(total_bedrooms=341.0)
Row(total_bedrooms=169.0)
Row(total_bedrooms=270.0)
Row(total_bedrooms=1017.0)
Row(total_bedrooms=473.0)
Row(total_bedrooms=312.0)
Row(total_bedrooms=348.0)
Row(total_bedrooms=322.0)
Row(total_bedrooms=500.0)
Row(total_bedrooms=457.0)
Row(total_bedrooms=483.0)
Row(total_bedrooms=1344.0)
Row(total_bedrooms=430.0)
Row(total_bedrooms=506.0)
Row(total_bedrooms=505.0)
Row(total_bedrooms=422.0)
Row(total_bedrooms=588.0)
Row(total_bedrooms=386.0)
Row(total_bedrooms=439.0)
Row(total_bedrooms=314.0)
Row(total_bedrooms=297.0)
Row(total_bedrooms=438.0)
Row(total_bedrooms=481.0)
Row(total_bedrooms=318.0)
Row(total_bedrooms=471.0)
Row(total_bedrooms=96.0)
Row(total_bedrooms=592.0)
Row(total_bedrooms=238.0)
Row(total_bedrooms=453.0)
Row(total_bedrooms=70.0)
Row(total_bedrooms=1006.0)
Row(total_bedrooms=579.0)
Row(total_bedrooms=1003.0)
Row(total_bedrooms=827.0)
Row(total_bedrooms=515.0)
Row(total_bedrooms=391.0)
Row(total_bedrooms=618.0)
Row(total_bedrooms=368.0)
Row(total_bedrooms=623.0)
Row(total_bedrooms=340.0)
Row(total_bedrooms=331.0)
Row(total_bedrooms=756.0)
Row(total_bedrooms=769.0)
Row(total_bedrooms=248.0)
Row(total_bedrooms=563.0)
Row(total_bedrooms=391.0)
Row(total_bedrooms=501.0)
Row(total_bedrooms=618.0)
Row(total_bedrooms=677.0)
Row(total_bedrooms=460.0)
Row(total_bedrooms=1516.0)
Row(total_bedrooms=606.0)
Row(total_bedrooms=1209.0)
Row(total_bedrooms=134.0)
Row(total_bedrooms=242.0)
Row(total_bedrooms=459.0)
Row(total_bedrooms=653.0)
Row(total_bedrooms=351.0)
Row(total_bedrooms=233.0)
Row(total_bedrooms=662.0)
Row(total_bedrooms=310.0)
Row(total_bedrooms=349.0)
Row(total_bedrooms=842.0)
Row(total_bedrooms=847.0)
Row(total_bedrooms=383.0)
Row(total_bedrooms=671.0)
Row(total_bedrooms=284.0)
Row(total_bedrooms=319.0)
Row(total_bedrooms=658.0)
Row(total_bedrooms=773.0)
Row(total_bedrooms=642.0)
Row(total_bedrooms=658.0)
Row(total_bedrooms=350.0)
Row(total_bedrooms=444.0)
Row(total_bedrooms=841.0)
Row(total_bedrooms=265.0)
Row(total_bedrooms=515.0)
Row(total_bedrooms=327.0)
Row(total_bedrooms=307.0)
Row(total_bedrooms=693.0)
Row(total_bedrooms=397.0)
Row(total_bedrooms=1081.0)
Row(total_bedrooms=284.0)
Row(total_bedrooms=416.0)
Row(total_bedrooms=411.0)
Row(total_bedrooms=713.0)
Row(total_bedrooms=522.0)
Row(total_bedrooms=443.0)
Row(total_bedrooms=109.0)
Row(total_bedrooms=748.0)
Row(total_bedrooms=191.0)
Row(total_bedrooms=302.0)
Row(total_bedrooms=1175.0)
Row(total_bedrooms=446.0)
Row(total_bedrooms=1187.0)
Row(total_bedrooms=229.0)
Row(total_bedrooms=520.0)
Row(total_bedrooms=227.0)
Row(total_bedrooms=428.0)
Row(total_bedrooms=269.0)
Row(total_bedrooms=187.0)
Row(total_bedrooms=555.0)
Row(total_bedrooms=370.0)
Row(total_bedrooms=242.0)
Row(total_bedrooms=398.0)
Row(total_bedrooms=518.0)
Row(total_bedrooms=445.0)
Row(total_bedrooms=314.0)
Row(total_bedrooms=363.0)
Row(total_bedrooms=588.0)
Row(total_bedrooms=206.0)
Row(total_bedrooms=333.0)
Row(total_bedrooms=1839.0)
Row(total_bedrooms=281.0)
Row(total_bedrooms=420.0)
Row(total_bedrooms=140.0)
Row(total_bedrooms=276.0)
Row(total_bedrooms=428.0)
Row(total_bedrooms=548.0)
Row(total_bedrooms=1636.0)
Row(total_bedrooms=250.0)
Row(total_bedrooms=1068.0)
Row(total_bedrooms=740.0)
Row(total_bedrooms=465.0)
Row(total_bedrooms=224.0)
Row(total_bedrooms=814.0)
Row(total_bedrooms=1024.0)
Row(total_bedrooms=691.0)
Row(total_bedrooms=190.0)
Row(total_bedrooms=585.0)
Row(total_bedrooms=31.0)
Row(total_bedrooms=607.0)
Row(total_bedrooms=357.0)
Row(total_bedrooms=398.0)
Row(total_bedrooms=38.0)
Row(total_bedrooms=496.0)
Row(total_bedrooms=297.0)
Row(total_bedrooms=232.0)
Row(total_bedrooms=209.0)
Row(total_bedrooms=738.0)
Row(total_bedrooms=465.0)
Row(total_bedrooms=517.0)
Row(total_bedrooms=378.0)
Row(total_bedrooms=358.0)
Row(total_bedrooms=851.0)
Row(total_bedrooms=554.0)
Row(total_bedrooms=211.0)
Row(total_bedrooms=552.0)
Row(total_bedrooms=162.0)
Row(total_bedrooms=694.0)
Row(total_bedrooms=727.0)
Row(total_bedrooms=236.0)
Row(total_bedrooms=545.0)
Row(total_bedrooms=284.0)
Row(total_bedrooms=363.0)
Row(total_bedrooms=771.0)
Row(total_bedrooms=903.0)
Row(total_bedrooms=1827.0)
Row(total_bedrooms=339.0)
Row(total_bedrooms=1406.0)
Row(total_bedrooms=933.0)
Row(total_bedrooms=438.0)
Row(total_bedrooms=1004.0)
Row(total_bedrooms=571.0)
Row(total_bedrooms=874.0)
Row(total_bedrooms=261.0)
Row(total_bedrooms=756.0)
Row(total_bedrooms=410.0)
Row(total_bedrooms=364.0)
Row(total_bedrooms=331.0)
Row(total_bedrooms=290.0)
Row(total_bedrooms=222.0)
Row(total_bedrooms=414.0)
Row(total_bedrooms=416.0)
Row(total_bedrooms=120.0)
Row(total_bedrooms=568.0)
Row(total_bedrooms=266.0)
Row(total_bedrooms=262.0)
Row(total_bedrooms=511.0)
Row(total_bedrooms=242.0)
Row(total_bedrooms=1820.0)
Row(total_bedrooms=411.0)
Row(total_bedrooms=484.0)
Row(total_bedrooms=423.0)
Row(total_bedrooms=339.0)
Row(total_bedrooms=292.0)
Row(total_bedrooms=662.0)
Row(total_bedrooms=462.0)
Row(total_bedrooms=274.0)
Row(total_bedrooms=1253.0)
Row(total_bedrooms=354.0)
Row(total_bedrooms=495.0)
Row(total_bedrooms=1062.0)
Row(total_bedrooms=490.0)
Row(total_bedrooms=176.0)
Row(total_bedrooms=229.0)
Row(total_bedrooms=316.0)
Row(total_bedrooms=741.0)
Row(total_bedrooms=450.0)
Row(total_bedrooms=327.0)
Row(total_bedrooms=477.0)
Row(total_bedrooms=948.0)
Row(total_bedrooms=4522.0)
Row(total_bedrooms=429.0)
Row(total_bedrooms=139.0)
Row(total_bedrooms=1512.0)
Row(total_bedrooms=412.0)
Row(total_bedrooms=72.0)
Row(total_bedrooms=541.0)
Row(total_bedrooms=528.0)
Row(total_bedrooms=716.0)
Row(total_bedrooms=410.0)
Row(total_bedrooms=532.0)
Row(total_bedrooms=436.0)
Row(total_bedrooms=486.0)
Row(total_bedrooms=636.0)
Row(total_bedrooms=347.0)
Row(total_bedrooms=1404.0)
Row(total_bedrooms=537.0)
Row(total_bedrooms=539.0)
Row(total_bedrooms=314.0)
Row(total_bedrooms=299.0)
Row(total_bedrooms=529.0)
Row(total_bedrooms=1055.0)
Row(total_bedrooms=320.0)
Row(total_bedrooms=859.0)
Row(total_bedrooms=469.0)
Row(total_bedrooms=374.0)
Row(total_bedrooms=570.0)
Row(total_bedrooms=222.0)
Row(total_bedrooms=516.0)
Row(total_bedrooms=3493.0)
Row(total_bedrooms=648.0)
Row(total_bedrooms=1467.0)
Row(total_bedrooms=459.0)
Row(total_bedrooms=202.0)
Row(total_bedrooms=713.0)
Row(total_bedrooms=610.0)
Row(total_bedrooms=593.0)
Row(total_bedrooms=516.0)
Row(total_bedrooms=264.0)
Row(total_bedrooms=282.0)
Row(total_bedrooms=306.0)
Row(total_bedrooms=369.0)
Row(total_bedrooms=268.0)
Row(total_bedrooms=586.0)
Row(total_bedrooms=1411.0)
Row(total_bedrooms=472.0)
Row(total_bedrooms=407.0)
Row(total_bedrooms=871.0)
Row(total_bedrooms=317.0)
Row(total_bedrooms=216.0)
Row(total_bedrooms=205.0)
Row(total_bedrooms=317.0)
Row(total_bedrooms=213.0)
Row(total_bedrooms=477.0)
Row(total_bedrooms=581.0)
Row(total_bedrooms=271.0)
Row(total_bedrooms=477.0)
Row(total_bedrooms=1065.0)
Row(total_bedrooms=154.0)
Row(total_bedrooms=950.0)
Row(total_bedrooms=438.0)
Row(total_bedrooms=96.0)
Row(total_bedrooms=428.0)
Row(total_bedrooms=595.0)
Row(total_bedrooms=358.0)
Row(total_bedrooms=784.0)
Row(total_bedrooms=489.0)
Row(total_bedrooms=315.0)
Row(total_bedrooms=482.0)
Row(total_bedrooms=419.0)
Row(total_bedrooms=152.0)
Row(total_bedrooms=579.0)
Row(total_bedrooms=216.0)
Row(total_bedrooms=460.0)
Row(total_bedrooms=360.0)
Row(total_bedrooms=673.0)
Row(total_bedrooms=161.0)
Row(total_bedrooms=417.0)
Row(total_bedrooms=379.0)
Row(total_bedrooms=1060.0)
Row(total_bedrooms=1185.0)
Row(total_bedrooms=435.0)
Row(total_bedrooms=72.0)
Row(total_bedrooms=390.0)
Row(total_bedrooms=685.0)
Row(total_bedrooms=319.0)
Row(total_bedrooms=528.0)
Row(total_bedrooms=652.0)
Row(total_bedrooms=714.0)
Row(total_bedrooms=930.0)
Row(total_bedrooms=400.0)
Row(total_bedrooms=265.0)
Row(total_bedrooms=629.0)
Row(total_bedrooms=589.0)
Row(total_bedrooms=345.0)
Row(total_bedrooms=460.0)
Row(total_bedrooms=373.0)
Row(total_bedrooms=245.0)
Row(total_bedrooms=165.0)
Row(total_bedrooms=470.0)
Row(total_bedrooms=1048.0)
Row(total_bedrooms=240.0)
Row(total_bedrooms=450.0)
Row(total_bedrooms=540.0)
Row(total_bedrooms=617.0)
Row(total_bedrooms=395.0)
Row(total_bedrooms=410.0)
Row(total_bedrooms=725.0)
Row(total_bedrooms=379.0)
Row(total_bedrooms=478.0)
Row(total_bedrooms=730.0)
Row(total_bedrooms=476.0)
Row(total_bedrooms=302.0)
Row(total_bedrooms=2441.0)
Row(total_bedrooms=388.0)
Row(total_bedrooms=243.0)
Row(total_bedrooms=544.0)
Row(total_bedrooms=956.0)
Row(total_bedrooms=87.0)
Row(total_bedrooms=300.0)
Row(total_bedrooms=314.0)
Row(total_bedrooms=1278.0)
Row(total_bedrooms=609.0)
Row(total_bedrooms=276.0)
Row(total_bedrooms=179.0)
Row(total_bedrooms=1025.0)
Row(total_bedrooms=682.0)
Row(total_bedrooms=372.0)
Row(total_bedrooms=484.0)
Row(total_bedrooms=579.0)
Row(total_bedrooms=289.0)
Row(total_bedrooms=1075.0)
Row(total_bedrooms=104.0)
Row(total_bedrooms=263.0)
Row(total_bedrooms=1185.0)
Row(total_bedrooms=798.0)
Row(total_bedrooms=306.0)
Row(total_bedrooms=1115.0)
Row(total_bedrooms=332.0)
Row(total_bedrooms=339.0)
Row(total_bedrooms=236.0)
Row(total_bedrooms=519.0)
Row(total_bedrooms=370.0)
Row(total_bedrooms=298.0)
Row(total_bedrooms=325.0)
Row(total_bedrooms=216.0)
Row(total_bedrooms=176.0)
Row(total_bedrooms=458.0)
Row(total_bedrooms=486.0)
Row(total_bedrooms=664.0)
Row(total_bedrooms=406.0)
Row(total_bedrooms=930.0)
Row(total_bedrooms=661.0)
Row(total_bedrooms=775.0)
Row(total_bedrooms=745.0)
Row(total_bedrooms=704.0)
Row(total_bedrooms=302.0)
Row(total_bedrooms=137.0)
Row(total_bedrooms=567.0)
Row(total_bedrooms=627.0)
Row(total_bedrooms=396.0)
Row(total_bedrooms=496.0)
Row(total_bedrooms=196.0)
Row(total_bedrooms=200.0)
Row(total_bedrooms=568.0)
Row(total_bedrooms=437.0)
Row(total_bedrooms=161.0)
Row(total_bedrooms=320.0)
Row(total_bedrooms=470.0)
Row(total_bedrooms=546.0)
Row(total_bedrooms=726.0)
Row(total_bedrooms=227.0)
Row(total_bedrooms=421.0)
Row(total_bedrooms=1011.0)
Row(total_bedrooms=260.0)
Row(total_bedrooms=373.0)
Row(total_bedrooms=408.0)
Row(total_bedrooms=232.0)
Row(total_bedrooms=430.0)
Row(total_bedrooms=1510.0)
Row(total_bedrooms=348.0)
Row(total_bedrooms=510.0)
Row(total_bedrooms=360.0)
Row(total_bedrooms=287.0)
Row(total_bedrooms=382.0)
Row(total_bedrooms=1281.0)
Row(total_bedrooms=438.0)
Row(total_bedrooms=327.0)
Row(total_bedrooms=744.0)
Row(total_bedrooms=303.0)
Row(total_bedrooms=233.0)
Row(total_bedrooms=86.0)
Row(total_bedrooms=283.0)
Row(total_bedrooms=369.0)
Row(total_bedrooms=230.0)
Row(total_bedrooms=203.0)
Row(total_bedrooms=199.0)
Row(total_bedrooms=278.0)
Row(total_bedrooms=282.0)
Row(total_bedrooms=187.0)
Row(total_bedrooms=292.0)
Row(total_bedrooms=264.0)
Row(total_bedrooms=1006.0)
Row(total_bedrooms=43.0)
Row(total_bedrooms=558.0)
Row(total_bedrooms=385.0)
Row(total_bedrooms=472.0)
Row(total_bedrooms=536.0)
Row(total_bedrooms=635.0)
Row(total_bedrooms=612.0)
Row(total_bedrooms=262.0)
Row(total_bedrooms=1005.0)
Row(total_bedrooms=514.0)
Row(total_bedrooms=147.0)
Row(total_bedrooms=260.0)
Row(total_bedrooms=752.0)
Row(total_bedrooms=472.0)
Row(total_bedrooms=584.0)
Row(total_bedrooms=544.0)
Row(total_bedrooms=447.0)
Row(total_bedrooms=364.0)
Row(total_bedrooms=564.0)
Row(total_bedrooms=782.0)
Row(total_bedrooms=547.0)
Row(total_bedrooms=372.0)
Row(total_bedrooms=1130.0)
Row(total_bedrooms=378.0)
Row(total_bedrooms=26.0)
Row(total_bedrooms=268.0)
Row(total_bedrooms=358.0)
Row(total_bedrooms=328.0)
Row(total_bedrooms=1979.0)
Row(total_bedrooms=314.0)
Row(total_bedrooms=309.0)
Row(total_bedrooms=751.0)
Row(total_bedrooms=832.0)
Row(total_bedrooms=536.0)
Row(total_bedrooms=249.0)
Row(total_bedrooms=513.0)
Row(total_bedrooms=335.0)
Row(total_bedrooms=256.0)
Row(total_bedrooms=631.0)
Row(total_bedrooms=241.0)
Row(total_bedrooms=298.0)
Row(total_bedrooms=731.0)
Row(total_bedrooms=565.0)
Row(total_bedrooms=828.0)
Row(total_bedrooms=362.0)
Row(total_bedrooms=185.0)
Row(total_bedrooms=301.0)
Row(total_bedrooms=229.0)
Row(total_bedrooms=795.0)
Row(total_bedrooms=704.0)
Row(total_bedrooms=560.0)
Row(total_bedrooms=413.0)
Row(total_bedrooms=220.0)
Row(total_bedrooms=562.0)
Row(total_bedrooms=1317.0)
Row(total_bedrooms=550.0)
Row(total_bedrooms=347.0)
Row(total_bedrooms=539.0)
Row(total_bedrooms=454.0)
Row(total_bedrooms=174.0)
Row(total_bedrooms=1617.0)
Row(total_bedrooms=510.0)
Row(total_bedrooms=177.0)
Row(total_bedrooms=538.0)
Row(total_bedrooms=402.0)
Row(total_bedrooms=519.0)
Row(total_bedrooms=251.0)
Row(total_bedrooms=552.0)
Row(total_bedrooms=288.0)
Row(total_bedrooms=19.0)
Row(total_bedrooms=1353.0)
Row(total_bedrooms=812.0)
Row(total_bedrooms=420.0)
Row(total_bedrooms=480.0)
Row(total_bedrooms=70.0)
Row(total_bedrooms=506.0)
Row(total_bedrooms=481.0)
Row(total_bedrooms=576.0)
Row(total_bedrooms=230.0)
Row(total_bedrooms=307.0)
Row(total_bedrooms=74.0)
Row(total_bedrooms=208.0)
Row(total_bedrooms=256.0)
Row(total_bedrooms=708.0)
Row(total_bedrooms=194.0)
Row(total_bedrooms=199.0)
Row(total_bedrooms=499.0)
Row(total_bedrooms=365.0)
Row(total_bedrooms=267.0)
Row(total_bedrooms=837.0)
Row(total_bedrooms=130.0)
Row(total_bedrooms=477.0)
Row(total_bedrooms=384.0)
Row(total_bedrooms=413.0)
Row(total_bedrooms=450.0)
Row(total_bedrooms=819.0)
Row(total_bedrooms=458.0)
Row(total_bedrooms=621.0)
Row(total_bedrooms=327.0)
Row(total_bedrooms=185.0)
Row(total_bedrooms=386.0)
Row(total_bedrooms=221.0)
Row(total_bedrooms=765.0)
Row(total_bedrooms=296.0)
Row(total_bedrooms=685.0)
Row(total_bedrooms=206.0)
Row(total_bedrooms=355.0)
Row(total_bedrooms=353.0)
Row(total_bedrooms=927.0)
Row(total_bedrooms=389.0)
Row(total_bedrooms=499.0)
Row(total_bedrooms=586.0)
Row(total_bedrooms=1346.0)
Row(total_bedrooms=365.0)
Row(total_bedrooms=706.0)
Row(total_bedrooms=890.0)
Row(total_bedrooms=273.0)
Row(total_bedrooms=352.0)
Row(total_bedrooms=300.0)
Row(total_bedrooms=174.0)
Row(total_bedrooms=388.0)
Row(total_bedrooms=269.0)
Row(total_bedrooms=1073.0)
Row(total_bedrooms=42.0)
Row(total_bedrooms=649.0)
Row(total_bedrooms=542.0)
Row(total_bedrooms=656.0)
Row(total_bedrooms=502.0)
Row(total_bedrooms=533.0)
Row(total_bedrooms=760.0)
Row(total_bedrooms=1302.0)
Row(total_bedrooms=322.0)
Row(total_bedrooms=763.0)
Row(total_bedrooms=584.0)
Row(total_bedrooms=232.0)
Row(total_bedrooms=598.0)
Row(total_bedrooms=901.0)
Row(total_bedrooms=206.0)
Row(total_bedrooms=435.0)
Row(total_bedrooms=464.0)
Row(total_bedrooms=283.0)
Row(total_bedrooms=535.0)
Row(total_bedrooms=476.0)
Row(total_bedrooms=489.0)
Row(total_bedrooms=130.0)
Row(total_bedrooms=97.0)
Row(total_bedrooms=19.0)
Row(total_bedrooms=819.0)
Row(total_bedrooms=299.0)
Row(total_bedrooms=1054.0)
Row(total_bedrooms=533.0)
Row(total_bedrooms=614.0)
Row(total_bedrooms=145.0)
Row(total_bedrooms=296.0)
Row(total_bedrooms=623.0)
Row(total_bedrooms=2495.0)
Row(total_bedrooms=230.0)
Row(total_bedrooms=395.0)
Row(total_bedrooms=283.0)
Row(total_bedrooms=630.0)
Row(total_bedrooms=666.0)
Row(total_bedrooms=418.0)
Row(total_bedrooms=598.0)
Row(total_bedrooms=274.0)
Row(total_bedrooms=451.0)
Row(total_bedrooms=132.0)
Row(total_bedrooms=267.0)
Row(total_bedrooms=852.0)
Row(total_bedrooms=530.0)
Row(total_bedrooms=203.0)
Row(total_bedrooms=786.0)
Row(total_bedrooms=8.0)
Row(total_bedrooms=139.0)
Row(total_bedrooms=584.0)
Row(total_bedrooms=756.0)
Row(total_bedrooms=273.0)
Row(total_bedrooms=98.0)
Row(total_bedrooms=716.0)
Row(total_bedrooms=1154.0)
Row(total_bedrooms=286.0)
Row(total_bedrooms=500.0)
Row(total_bedrooms=20.0)
Row(total_bedrooms=545.0)
Row(total_bedrooms=609.0)
Row(total_bedrooms=1139.0)
Row(total_bedrooms=735.0)
Row(total_bedrooms=291.0)
Row(total_bedrooms=496.0)
Row(total_bedrooms=456.0)
Row(total_bedrooms=101.0)
Row(total_bedrooms=276.0)
Row(total_bedrooms=1074.0)
Row(total_bedrooms=527.0)
Row(total_bedrooms=1191.0)
Row(total_bedrooms=1084.0)
Row(total_bedrooms=809.0)
Row(total_bedrooms=479.0)
Row(total_bedrooms=470.0)
Row(total_bedrooms=89.0)
Row(total_bedrooms=669.0)
Row(total_bedrooms=548.0)
Row(total_bedrooms=469.0)
Row(total_bedrooms=216.0)
Row(total_bedrooms=393.0)
Row(total_bedrooms=322.0)
Row(total_bedrooms=675.0)
Row(total_bedrooms=183.0)
Row(total_bedrooms=413.0)
Row(total_bedrooms=299.0)
Row(total_bedrooms=463.0)
Row(total_bedrooms=74.0)
Row(total_bedrooms=1010.0)
Row(total_bedrooms=416.0)
Row(total_bedrooms=908.0)
Row(total_bedrooms=493.0)
Row(total_bedrooms=181.0)
Row(total_bedrooms=185.0)
Row(total_bedrooms=394.0)
Row(total_bedrooms=256.0)
Row(total_bedrooms=280.0)
Row(total_bedrooms=159.0)
Row(total_bedrooms=248.0)
Row(total_bedrooms=583.0)
Row(total_bedrooms=140.0)
Row(total_bedrooms=834.0)
Row(total_bedrooms=402.0)
Row(total_bedrooms=430.0)
Row(total_bedrooms=1222.0)
Row(total_bedrooms=716.0)
Row(total_bedrooms=547.0)
Row(total_bedrooms=246.0)
Row(total_bedrooms=1067.0)
Row(total_bedrooms=200.0)
Row(total_bedrooms=432.0)
Row(total_bedrooms=493.0)
Row(total_bedrooms=512.0)
Row(total_bedrooms=323.0)
Row(total_bedrooms=701.0)
Row(total_bedrooms=8.0)
Row(total_bedrooms=316.0)
Row(total_bedrooms=605.0)
Row(total_bedrooms=347.0)
Row(total_bedrooms=400.0)
Row(total_bedrooms=604.0)
Row(total_bedrooms=62.0)
Row(total_bedrooms=4.0)
Row(total_bedrooms=397.0)
Row(total_bedrooms=13.0)
Row(total_bedrooms=502.0)
Row(total_bedrooms=274.0)
Row(total_bedrooms=985.0)
Row(total_bedrooms=597.0)
Row(total_bedrooms=563.0)
Row(total_bedrooms=531.0)
Row(total_bedrooms=1282.0)
Row(total_bedrooms=479.0)
Row(total_bedrooms=884.0)
Row(total_bedrooms=460.0)
Row(total_bedrooms=2062.0)
Row(total_bedrooms=368.0)
Row(total_bedrooms=899.0)
Row(total_bedrooms=658.0)
Row(total_bedrooms=691.0)
Row(total_bedrooms=356.0)
Row(total_bedrooms=422.0)
Row(total_bedrooms=776.0)
Row(total_bedrooms=433.0)
Row(total_bedrooms=753.0)
Row(total_bedrooms=312.0)
Row(total_bedrooms=195.0)
Row(total_bedrooms=690.0)
Row(total_bedrooms=384.0)

In [ ]:
first_row = house_df.first()
print(first_row)

Row(total_bedrooms=661.0)

In [ ]:
df= spark.read.csv("/content/sample_data/california_housing_test.csv", header=True, inferSchema=True)

In [ ]:
df.show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|  -122.05|   37.37|              27.0|     3885.0|         661.0|    1537.0|     606.0|       6.6085|          344700.0|
|   -118.3|   34.26|              43.0|     1510.0|         310.0|     809.0|     277.0|        3.599|          176500.0|
|  -117.81|   33.78|              27.0|     3589.0|         507.0|    1484.0|     495.0|       5.7934|          270500.0|
|  -118.36|   33.82|              28.0|       67.0|          15.0|      49.0|      11.0|       6.1359|          330000.0|
|  -119.67|   36.33|              19.0|     1241.0|         244.0|     850.0|     237.0|       2.9375|           81700.0|
|  -119.56|   36.51|              37.0|     1018.0|         213.0|     663.0|     204.0|       1.6635|           67000.0|
|  -121.43|   38.63|              43.0|     1009.0|         225.0|     604.0|     218.0|       1.6641|           67000.0|
|  -120.65|   35.48|              19.0|     2310.0|         471.0|    1341.0|     441.0|        3.225|          166900.0|
|  -122.84|    38.4|              15.0|     3080.0|         617.0|    1446.0|     599.0|       3.6696|          194400.0|
|  -118.02|   34.08|              31.0|     2402.0|         632.0|    2830.0|     603.0|       2.3333|          164200.0|
|  -118.24|   33.98|              45.0|      972.0|         249.0|    1288.0|     261.0|       2.2054|          125000.0|
|  -119.12|   35.85|              37.0|      736.0|         166.0|     564.0|     138.0|       2.4167|           58300.0|
|  -121.93|   37.25|              36.0|     1089.0|         182.0|     535.0|     170.0|         4.69|          252600.0|
|  -117.03|   32.97|              16.0|     3936.0|         694.0|    1935.0|     659.0|       4.5625|          231200.0|
|  -117.97|   33.73|              27.0|     2097.0|         325.0|    1217.0|     331.0|       5.7121|          222500.0|
|  -117.99|   33.81|              42.0|      161.0|          40.0|     157.0|      50.0|          2.2|          153100.0|
|  -120.81|   37.53|              15.0|      570.0|         123.0|     189.0|     107.0|        1.875|          181300.0|
|   -121.2|   38.69|              26.0|     3077.0|         607.0|    1603.0|     595.0|       2.7174|          137500.0|
|  -118.88|   34.21|              26.0|     1590.0|         196.0|     654.0|     199.0|       6.5851|          300000.0|
|  -122.59|   38.01|              35.0|     8814.0|        1307.0|    3450.0|    1258.0|       6.1724|          414300.0|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
only showing top 20 rows

In [ ]:
#sort the column in descending order

#sorted_df = df.orderBy(df.Age.desc())
#sorted_df.show()
df.orderBy("population")
df.orderBy(df.population.desc()).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|  -121.53|   38.48|               5.0|    27870.0|        5027.0|   11935.0|    4855.0|       4.8811|          212200.0|
|  -116.14|   34.45|              12.0|     8796.0|        1721.0|   11139.0|    1680.0|       2.2612|          137500.0|
|  -117.27|   33.15|               4.0|    23915.0|        4135.0|   10877.0|    3958.0|       4.6357|          244900.0|
|   -117.2|   33.58|               2.0|    30450.0|        5033.0|    9419.0|    3197.0|       4.5936|          174300.0|
|  -117.12|   33.49|               4.0|    21988.0|        4055.0|    8824.0|    3252.0|       3.9963|          191100.0|
|  -121.73|   37.68|              17.0|    20354.0|        3493.0|    8768.0|    3293.0|       5.4496|          238900.0|
|  -118.08|   34.55|               5.0|    16181.0|        2971.0|    8152.0|    2651.0|       4.5237|          141800.0|
|  -117.22|   32.86|               4.0|    16289.0|        4585.0|    7604.0|    4176.0|       3.6287|          280800.0|
|  -117.23|   33.91|               9.0|    11654.0|        2100.0|    7596.0|    2127.0|       4.0473|          127200.0|
|  -117.18|   32.92|               4.0|    15025.0|        2616.0|    7560.0|    2392.0|        5.196|          210700.0|
|  -118.44|   33.98|              21.0|    18132.0|        5419.0|    7431.0|    4930.0|       5.3359|          500001.0|
|  -117.71|   34.02|              17.0|    12689.0|        2426.0|    7343.0|    2230.0|       3.6361|          157700.0|
|  -117.04|    32.7|               7.0|     9311.0|        1703.0|    7302.0|    1694.0|        4.419|          156900.0|
|  -117.22|   32.95|               4.0|    18123.0|        3173.0|    7301.0|    2964.0|        6.357|          322500.0|
|  -121.42|   38.49|              17.0|    13180.0|        2444.0|    7235.0|    2335.0|        3.363|          103000.0|
|  -121.87|   37.42|              19.0|    12128.0|        2112.0|    6810.0|    2040.0|       6.4419|          264500.0|
|  -121.15|   38.69|              52.0|      240.0|          44.0|    6675.0|      29.0|       6.1359|          225000.0|
|  -117.58|   34.11|              14.0|    11635.0|        2055.0|    6443.0|    2009.0|       4.7547|          157600.0|
|  -117.23|   32.88|              18.0|     5566.0|        1465.0|    6303.0|    1458.0|        1.858|          205000.0|
|   -117.7|   33.48|               6.0|    16590.0|        2696.0|    6223.0|    2357.0|       6.3088|          340300.0|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
only showing top 20 rows

In [ ]:
#sort the column
sorted_df = df.sort(col("population").desc())
sorted_df.show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|  -121.53|   38.48|               5.0|    27870.0|        5027.0|   11935.0|    4855.0|       4.8811|          212200.0|
|  -116.14|   34.45|              12.0|     8796.0|        1721.0|   11139.0|    1680.0|       2.2612|          137500.0|
|  -117.27|   33.15|               4.0|    23915.0|        4135.0|   10877.0|    3958.0|       4.6357|          244900.0|
|   -117.2|   33.58|               2.0|    30450.0|        5033.0|    9419.0|    3197.0|       4.5936|          174300.0|
|  -117.12|   33.49|               4.0|    21988.0|        4055.0|    8824.0|    3252.0|       3.9963|          191100.0|
|  -121.73|   37.68|              17.0|    20354.0|        3493.0|    8768.0|    3293.0|       5.4496|          238900.0|
|  -118.08|   34.55|               5.0|    16181.0|        2971.0|    8152.0|    2651.0|       4.5237|          141800.0|
|  -117.22|   32.86|               4.0|    16289.0|        4585.0|    7604.0|    4176.0|       3.6287|          280800.0|
|  -117.23|   33.91|               9.0|    11654.0|        2100.0|    7596.0|    2127.0|       4.0473|          127200.0|
|  -117.18|   32.92|               4.0|    15025.0|        2616.0|    7560.0|    2392.0|        5.196|          210700.0|
|  -118.44|   33.98|              21.0|    18132.0|        5419.0|    7431.0|    4930.0|       5.3359|          500001.0|
|  -117.71|   34.02|              17.0|    12689.0|        2426.0|    7343.0|    2230.0|       3.6361|          157700.0|
|  -117.04|    32.7|               7.0|     9311.0|        1703.0|    7302.0|    1694.0|        4.419|          156900.0|
|  -117.22|   32.95|               4.0|    18123.0|        3173.0|    7301.0|    2964.0|        6.357|          322500.0|
|  -121.42|   38.49|              17.0|    13180.0|        2444.0|    7235.0|    2335.0|        3.363|          103000.0|
|  -121.87|   37.42|              19.0|    12128.0|        2112.0|    6810.0|    2040.0|       6.4419|          264500.0|
|  -121.15|   38.69|              52.0|      240.0|          44.0|    6675.0|      29.0|       6.1359|          225000.0|
|  -117.58|   34.11|              14.0|    11635.0|        2055.0|    6443.0|    2009.0|       4.7547|          157600.0|
|  -117.23|   32.88|              18.0|     5566.0|        1465.0|    6303.0|    1458.0|        1.858|          205000.0|
|   -117.7|   33.48|               6.0|    16590.0|        2696.0|    6223.0|    2357.0|       6.3088|          340300.0|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
only showing top 20 rows

In [ ]:
#Group By Column
Grouped_df = df.groupby("latitude").agg({"population":"Sum"})
Grouped_df.show()

+--------+---------------+
|latitude|sum(population)|
+--------+---------------+
|   38.61|         9716.0|
|   37.81|         6565.0|
|   35.17|         1998.0|
|   37.23|         4067.0|
|   38.93|          494.0|
|   38.68|         9096.0|
|   35.15|         2293.0|
|   37.42|         6862.0|
|   35.38|          734.0|
|   37.29|        10681.0|
|   39.97|          625.0|
|   36.12|          356.0|
|   35.34|         1933.0|
|   37.68|        26412.0|
|   34.02|        60692.0|
|   33.68|         9726.0|
|   40.12|           35.0|
|   41.63|         1108.0|
|   38.26|        10566.0|
|   39.75|         5006.0|
+--------+---------------+
only showing top 20 rows

In [ ]:
Grouped_df.count()

587

In [ ]:
#Creating dataframe
data = [("Aman",'IT',30000,'New Delhi',2000), ("Abhi", 'UI',35000,'Haryana',1200),\
 ("Annu", 'IT',35000,'Punjab',1200),("Akshay", 'IT',25000,'New Delhi',1500),("Abhi", 'UI',40000,'Haryana',1000)]
df = spark.createDataFrame(data, ["Name", "department","salary","State","Incentive"])
print("Original Dataframe")
df.show()

Original Dataframe
+------+----------+------+---------+---------+
|  Name|department|salary|    State|Incentive|
+------+----------+------+---------+---------+
|  Aman|        IT| 30000|New Delhi|     2000|
|  Abhi|        UI| 35000|  Haryana|     1200|
|  Annu|        IT| 35000|   Punjab|     1200|
|Akshay|        IT| 25000|New Delhi|     1500|
|  Abhi|        UI| 40000|  Haryana|     1000|
+------+----------+------+---------+---------+

In [ ]:
#Group by on multiple columns
grouped_df = df.groupby("department","state").sum("salary","Incentive")
print('After Groupby on the department and state')
grouped_df.show()

print("Adding name columnn in group by")
df.groupby("Name","department","state").sum("salary","Incentive").show()

After Groupby on the department and state
+----------+---------+-----------+--------------+
|department|    state|sum(salary)|sum(Incentive)|
+----------+---------+-----------+--------------+
|        IT|New Delhi|      55000|          3500|
|        UI|  Haryana|      75000|          2200|
|        IT|   Punjab|      35000|          1200|
+----------+---------+-----------+--------------+

Adding name columnn in group by
+------+----------+---------+-----------+--------------+
|  Name|department|    state|sum(salary)|sum(Incentive)|
+------+----------+---------+-----------+--------------+
|  Abhi|        UI|  Haryana|      75000|          2200|
|  Aman|        IT|New Delhi|      30000|          2000|
|Akshay|        IT|New Delhi|      25000|          1500|
|  Annu|        IT|   Punjab|      35000|          1200|
+------+----------+---------+-----------+--------------+

In [ ]:
#Aliasing in groupby
from pyspark.sql.functions import sum,avg,max
df.groupby("department")\
  .agg(sum("salary").alias("Sum_salary"),\
     avg("salary").alias("Avg_salary"),\
     sum("Incentive").alias("Sum_bonus"),\
     max("Incentive").alias("Max_bonus"),\
).show()

+----------+----------+----------+---------+---------+
|department|Sum_salary|Avg_salary|Sum_bonus|Max_bonus|
+----------+----------+----------+---------+---------+
|        UI|     75000|   37500.0|     2200|     1200|
|        IT|     90000|   30000.0|     4700|     2000|
+----------+----------+----------+---------+---------+

In [ ]:
#filter condition in group by
print("with filer condition where bonus is greater than 2500")
df.groupby("department")\
  .agg(sum("salary").alias("Sum_salary"),\
     avg("salary").alias("Avg_salary"),\
     sum("Incentive").alias("Sum_bonus"),\
     max("Incentive").alias("Max_bonus"))\
    .where(col("sum_bonus") >= 2500).show()

with filer condition where bonus is greater than 2500
+----------+----------+----------+---------+---------+
|department|Sum_salary|Avg_salary|Sum_bonus|Max_bonus|
+----------+----------+----------+---------+---------+
|        IT|     90000|   30000.0|     4700|     2000|
+----------+----------+----------+---------+---------+

In [ ]:
#filter condition in group by
print("with filer condition where bonus is less than 2500")
df.groupby("department")\
  .agg(sum("salary").alias("Sum_salary"),\
     avg("salary").alias("Avg_salary"),\
     sum("Incentive").alias("Sum_bonus"),\
     max("Incentive").alias("Max_bonus"))\
    .where(col("sum_bonus") <= 2500).show()

with filer condition where bonus is less than 2500
+----------+----------+----------+---------+---------+
|department|Sum_salary|Avg_salary|Sum_bonus|Max_bonus|
+----------+----------+----------+---------+---------+
|        UI|     75000|   37500.0|     2200|     1200|
+----------+----------+----------+---------+---------+

In [ ]:
##data for union
Data1 = [("James","Sales","NY",90000,34,10000), \
    ("Michael","Sales","NY",86000,56,20000), \
    ("Robert","Sales","CA",81000,30,23000), \
    ("Maria","Finance","CA",90000,24,23000) ]

columns= ["employee_name","department","state","salary","age","bonus"]
df = spark.createDataFrame(data = Data1, schema = columns)
# df.printSchema()
print('First df')
df.show()

Data2 = [("James","Sales","NY",90000,34,10000), \
    ("Maria","Finance","CA",90000,24,23000), \
    ("Jen","Finance","NY",79000,53,15000), \
    ("Jeff","Marketing","CA",80000,25,18000), \
    ("Kumar","Marketing","NY",91000,50,21000)]
columns2= ["employee_name","department","state","salary","age","bonus"]

df2 = spark.createDataFrame(data = Data2, schema = columns2)
# df2.printSchema()
print('Second df')
df2.show()
#Union of two datasets
unionDF= df.union(df2)
print("First DF union second df")
unionDF.show()
#distinct records after union
print("using distinct")
disDF= df.union(df2).distinct()
disDF.show()

First df
+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
+-------------+----------+-----+------+---+-----+

Second df
+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
+-------------+----------+-----+------+---+-----+

First DF union second df
+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        James|     Sales|   NY| 90000| 34|10000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
+-------------+----------+-----+------+---+-----+

using distinct
+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Kumar| Marketing|   NY| 91000| 50|21000|
|          Jen|   Finance|   NY| 79000| 53|15000|
|         Jeff| Marketing|   CA| 80000| 25|18000|
+-------------+----------+-----+------+---+-----+

In [ ]:
Data3 = [("Peter",90000,"Sales","NY",34), \
    ("Carl",9000,"Finance","CA",24), \
    ("Jason",79000,"Finance","NY",53), \
    ("Alex",80000,"Marketing","CA",25), \
    ("Leo",91000,"Marketing","NY",50)]
columns3= ["employee_name","salary","department","state","age"]

df3 = spark.createDataFrame(data = Data3, schema = columns3)
# df3.printSchema()
print('Third df')
df3.show()

Third df
+-------------+------+----------+-----+---+
|employee_name|salary|department|state|age|
+-------------+------+----------+-----+---+
|        Peter| 90000|     Sales|   NY| 34|
|         Carl|  9000|   Finance|   CA| 24|
|        Jason| 79000|   Finance|   NY| 53|
|         Alex| 80000| Marketing|   CA| 25|
|          Leo| 91000| Marketing|   NY| 50|
+-------------+------+----------+-----+---+

In [ ]:
#unionbyName is used to union the datasets where datasets schema is not same
byNameDF= df.unionByName(df3,allowMissingColumns=True)
print("UnionByName result")
byNameDF.show()

UnionByName result
+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Peter|     Sales|   NY| 90000| 34| null|
|         Carl|   Finance|   CA|  9000| 24| null|
|        Jason|   Finance|   NY| 79000| 53| null|
|         Alex| Marketing|   CA| 80000| 25| null|
|          Leo| Marketing|   NY| 91000| 50| null|
+-------------+----------+-----+------+---+-----+

In [ ]:
##Renaming columns
df3= df3.withColumnRenamed("bonus","Incentive")
df3.show()

+-------------+------+----------+-----+---+
|employee_name|salary|department|state|age|
+-------------+------+----------+-----+---+
|        Peter| 90000|     Sales|   NY| 34|
|         Carl|  9000|   Finance|   CA| 24|
|        Jason| 79000|   Finance|   NY| 53|
|         Alex| 80000| Marketing|   CA| 25|
|          Leo| 91000| Marketing|   NY| 50|
+-------------+------+----------+-----+---+

In [ ]:
#Drop duplicates and distinct
Data = [("James","Sales","NY",90000,34,10000), \
    ("Michael","Sales","NY",86000,56,20000), \
    ("Robert","Sales","CA",81000,30,23000), \
    ("Maria","Finance","CA",90000,24,23000),\
    ("Maria","Finance","CA",90000,24,23000),\
    ("Michael","Sales","NY",86000,56,20000)  ]
columns= ["employee_name","department","state","salary","age","bonus"]
df = spark.createDataFrame(data = Data, schema = columns)
print("Original DF")
df.show()
print("Dropping columns")
df = df.dropDuplicates(["department","salary"])
df.show()

Original DF
+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|      Michael|     Sales|   NY| 86000| 56|20000|
+-------------+----------+-----+------+---+-----+

Dropping columns
+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        Maria|   Finance|   CA| 90000| 24|23000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|        James|     Sales|   NY| 90000| 34|10000|
+-------------+----------+-----+------+---+-----+

In [ ]:
from pyspark import Row
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()
# from pyspark.shell import spark

df = spark.createDataFrame([
Row(Roll_no=None, Date='20151231', Data='Hello'),
Row(Roll_no=2, Date='20160101', Data=None),
Row(Roll_no=3, Date=None, Data='World')
])

df.write.csv('/content/sample_data/practice1.csv', header=True, emptyValue='')

In [ ]:
df= spark.read.csv('/content/sample_data/practice1.csv', header=True, inferSchema=True)

In [ ]:
df.show()

+-------+--------+-----+
|Roll_no|    Date| Data|
+-------+--------+-----+
|      2|20160101| null|
|      3|    null|World|
|   null|20151231|Hello|
+-------+--------+-----+

In [ ]:
print("Fill Null values in Roll_no with a specific value")
df = df.fillna({"Roll_no": 4})
df.show()

print("replace 0 for null all integer columns")
df = df.na.fill(value = 0)
df.show()

print("replace 0 for null on only population column")
df = df.na.fill(value = 'NoData',subset =["Data"])
df.show()

Fill Null values in Roll_no with a specific value
+-------+--------+-----+
|Roll_no|    Date| Data|
+-------+--------+-----+
|      2|20160101| null|
|      3|    null|World|
|      4|20151231|Hello|
+-------+--------+-----+

replace 0 for null all integer columns
+-------+--------+-----+
|Roll_no|    Date| Data|
+-------+--------+-----+
|      2|20160101| null|
|      3|       0|World|
|      4|20151231|Hello|
+-------+--------+-----+

replace 0 for null on only population column
+-------+--------+------+
|Roll_no|    Date|  Data|
+-------+--------+------+
|      2|20160101|NoData|
|      3|       0| World|
|      4|20151231| Hello|
+-------+--------+------+

In [ ]:
from pyspark import Row
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()
# from pyspark.shell import spark

df = spark.createDataFrame([
    Row(Roll_no=None, Date='20151231', Data='Hello'),
    Row(Roll_no=2, Date='20160101', Data=None),
    Row(Roll_no=None, Date=None, Data=None)
])

df.write.csv('/content/sample_data/practice14.csv', header=True, emptyValue='')

df_1=spark.read.csv('/content/sample_data/practice14.csv', header=True,inferSchema=True)
print("original data")
df_1.show()
#drop null values
print("drop nulls values")
df_1=df_1.dropna(how="all")
df_1.show()

original data
+-------+--------+-----+
|Roll_no|    Date| Data|
+-------+--------+-----+
|   null|20151231|Hello|
|      2|20160101| null|
|   null|    null| null|
+-------+--------+-----+

drop nulls values
+-------+--------+-----+
|Roll_no|    Date| Data|
+-------+--------+-----+
|   null|20151231|Hello|
|      2|20160101| null|
+-------+--------+-----+

In [ ]:
#Creating dataframe
Data = [("James","Sales","NY",90000,34,10000), \
    ("Michael","Sales","NY",86000,56,20000), \
    ("Robert","Sales","CA",81000,30,23000), \
    ("Maria","Finance","CA",90000,24,23000),\
    ("Maria","Finance","CA",90000,24,23000),\
    ("Michael","Sales","NY",86000,56,20000)  ]
columns= ["employee_name","department","state","salary","age","bonus"]
df = spark.createDataFrame(data = Data, schema = columns)
df.show()
print("after applying pivot")
pivoted_df = df.groupBy("employee_name").pivot("department").sum("bonus")
pivoted_df.show()

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|        James|     Sales|   NY| 90000| 34|10000|
|      Michael|     Sales|   NY| 86000| 56|20000|
|       Robert|     Sales|   CA| 81000| 30|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|        Maria|   Finance|   CA| 90000| 24|23000|
|      Michael|     Sales|   NY| 86000| 56|20000|
+-------------+----------+-----+------+---+-----+

after applying pivot
+-------------+-------+-----+
|employee_name|Finance|Sales|
+-------------+-------+-----+
|        James|   null|10000|
|      Michael|   null|40000|
|        Maria|  46000| null|
|       Robert|   null|23000|
+-------------+-------+-----+

In [ ]:
print("DAY 3")

DAY 3

In [ ]:
#Creating two Dataframes
df1 = spark.createDataFrame([(23, 'Aarav'), (42, 'Daisy'), (37, 'Avi'),(43, 'Abir'),(11, 'Raghav'),(19, 'Nitara')], ['roll_no', 'student_name'])
print('df1')
df1.show()
df2 = spark.createDataFrame([(42, 'English'), (37, 'Maths'), (19, 'Computer Science'),(8, 'Sociology'),(16, 'IT'),(23, 'Hindi')], ['roll_no', 'Subject_Name'])
print('df2')
df2.show()

#Inner join example
inner_join = df1.join(df2, on='roll_no',how='inner')
print('INNER JOIN')
inner_join.show()

#Right join example
right_join = df1.join(df2, on='roll_no',how='right')
print('RIGHT JOIN')
right_join.show()

#Left join example
left_join = df1.join(df2, on='roll_no',how='left')
print('LEFT JOIN')
left_join.show()

#Full outer join
full_outer_join = df1.join(df2, on='roll_no',how='outer')
print('FULL OUTER JOIN')
full_outer_join.show()

# Left semi join
Left_semi_join = df1.join(df2, on='roll_no',how='leftsemi')
print('LEFT SEMI JOIN')
Left_semi_join.show()

# Left anti join
Left_anti_join = df1.join(df2, on='roll_no',how='leftanti')
print('LEFT ANTI JOIN')
Left_anti_join.show()

df1
+-------+------------+
|roll_no|student_name|
+-------+------------+
|     23|       Aarav|
|     42|       Daisy|
|     37|         Avi|
|     43|        Abir|
|     11|      Raghav|
|     19|      Nitara|
+-------+------------+

df2
+-------+----------------+
|roll_no|    Subject_Name|
+-------+----------------+
|     42|         English|
|     37|           Maths|
|     19|Computer Science|
|      8|       Sociology|
|     16|              IT|
|     23|           Hindi|
+-------+----------------+

INNER JOIN
+-------+------------+----------------+
|roll_no|student_name|    Subject_Name|
+-------+------------+----------------+
|     19|      Nitara|Computer Science|
|     23|       Aarav|           Hindi|
|     37|         Avi|           Maths|
|     42|       Daisy|         English|
+-------+------------+----------------+

RIGHT JOIN
+-------+------------+----------------+
|roll_no|student_name|    Subject_Name|
+-------+------------+----------------+
|     19|      Nitara|Computer Science|
|     37|         Avi|           Maths|
|     42|       Daisy|         English|
|      8|        null|       Sociology|
|     23|       Aarav|           Hindi|
|     16|        null|              IT|
+-------+------------+----------------+

LEFT JOIN
+-------+------------+----------------+
|roll_no|student_name|    Subject_Name|
+-------+------------+----------------+
|     37|         Avi|           Maths|
|     42|       Daisy|         English|
|     23|       Aarav|           Hindi|
|     19|      Nitara|Computer Science|
|     43|        Abir|            null|
|     11|      Raghav|            null|
+-------+------------+----------------+

FULL OUTER JOIN
+-------+------------+----------------+
|roll_no|student_name|    Subject_Name|
+-------+------------+----------------+
|      8|        null|       Sociology|
|     11|      Raghav|            null|
|     16|        null|              IT|
|     19|      Nitara|Computer Science|
|     23|       Aarav|           Hindi|
|     37|         Avi|           Maths|
|     42|       Daisy|         English|
|     43|        Abir|            null|
+-------+------------+----------------+

LEFT SEMI JOIN
+-------+------------+
|roll_no|student_name|
+-------+------------+
|     19|      Nitara|
|     23|       Aarav|
|     37|         Avi|
|     42|       Daisy|
+-------+------------+

LEFT ANTI JOIN
+-------+------------+
|roll_no|student_name|
+-------+------------+
|     43|        Abir|
|     11|      Raghav|
+-------+------------+

In [ ]:
from pyspark.sql.functions import split
df1 = spark.createDataFrame([(1, 'Madgaon,Goa'), (2, 'Sonepat,Haryana'), (3, 'Gohana,Haryana'),(4, 'Delhi,NewDelhi'),(5, 'Ambala,Haryana'),(6, 'Gurugram,Haryana')], ['Id', 'Address'])
print('df1')
df1.show()


print("After Split -->")
# split_df = df1.withColumns('City', split(df1['Address'], ',')[0]).withColumns('State', split(df1['Address'], ',')[1])
df_split = df1.withColumn('City', split(df1['Address'], ',')[0])\
.withColumn('State', split(df1['Address'], ',')[1])
df_split.show()

df1
+---+----------------+
| Id|         Address|
+---+----------------+
|  1|     Madgaon,Goa|
|  2| Sonepat,Haryana|
|  3|  Gohana,Haryana|
|  4|  Delhi,NewDelhi|
|  5|  Ambala,Haryana|
|  6|Gurugram,Haryana|
+---+----------------+

After Split -->
+---+----------------+--------+--------+
| Id|         Address|    City|   State|
+---+----------------+--------+--------+
|  1|     Madgaon,Goa| Madgaon|     Goa|
|  2| Sonepat,Haryana| Sonepat| Haryana|
|  3|  Gohana,Haryana|  Gohana| Haryana|
|  4|  Delhi,NewDelhi|   Delhi|NewDelhi|
|  5|  Ambala,Haryana|  Ambala| Haryana|
|  6|Gurugram,Haryana|Gurugram| Haryana|
+---+----------------+--------+--------+

In [ ]:
#Length
from pyspark.sql import functions as F
length_col = F.length(df_split['State'])
df_split.withColumn('state_length',length_col).show()

+---+----------------+--------+--------+------------+
| Id|         Address|    City|   State|state_length|
+---+----------------+--------+--------+------------+
|  1|     Madgaon,Goa| Madgaon|     Goa|           3|
|  2| Sonepat,Haryana| Sonepat| Haryana|           7|
|  3|  Gohana,Haryana|  Gohana| Haryana|           7|
|  4|  Delhi,NewDelhi|   Delhi|NewDelhi|           8|
|  5|  Ambala,Haryana|  Ambala| Haryana|           7|
|  6|Gurugram,Haryana|Gurugram| Haryana|           7|
+---+----------------+--------+--------+------------+

In [ ]:
#regexp_replace
from pyspark.sql.functions import regexp_replace
print("After using regexp_replace ")
df_split.withColumn('state',regexp_replace('state','NewDelhi','New Delhi')).show()

After using regexp_replace
+---+----------------+--------+---------+
| Id|         Address|    City|    state|
+---+----------------+--------+---------+
|  1|     Madgaon,Goa| Madgaon|      Goa|
|  2| Sonepat,Haryana| Sonepat|  Haryana|
|  3|  Gohana,Haryana|  Gohana|  Haryana|
|  4|  Delhi,NewDelhi|   Delhi|New Delhi|
|  5|  Ambala,Haryana|  Ambala|  Haryana|
|  6|Gurugram,Haryana|Gurugram|  Haryana|
+---+----------------+--------+---------+

In [ ]:
#Creating a dataframe with a string column
from pyspark.sql import functions as F
data=[('     Hello There!!   ',)]
df=spark.createDataFrame(data,['Message'])
df.show()

#removing spaces

trim_col=F.trim(df['Message'])
df.withColumn('trimmed message',trim_col).show()

+--------------------+
|             Message|
+--------------------+
|     Hello There!...|
+--------------------+

+--------------------+---------------+
|             Message|trimmed message|
+--------------------+---------------+
|     Hello There!...|  Hello There!!|
+--------------------+---------------+

In [ ]:
#Casting
from pyspark.sql.pandas.conversion import IntegerType
df=spark.createDataFrame([(40,)],['number'])
print('Before')
df.dtypes
df.show()

# casting
df=df.withColumn('number',df.number.cast(IntegerType()))
print('After casting')
df.show()
df.dtypes

Before
+------+
|number|
+------+
|    40|
+------+

After casting
+------+
|number|
+------+
|    40|
+------+

[('number', 'int')]

In [ ]:
#Creating dataframe into date
from pyspark.sql.functions import *
df=spark.createDataFrame([["02-03-2013"],["05-06-2023"]],["input"])
df.printSchema()

df= df.select(col("input"),to_date(col("input"),"dd-MM-yyyy").alias("date"))
df.show()
df.printSchema()

root
 |-- input: string (nullable = true)

+----------+----------+
|     input|      date|
+----------+----------+
|02-03-2013|2013-03-02|
|05-06-2023|2023-06-05|
+----------+----------+

root
 |-- input: string (nullable = true)
 |-- date: date (nullable = true)

In [ ]:
#Concatenating two columns
from pyspark.sql.functions import concat,col
data = [('James','','Smith','1991-04-01','M',3000),
  ('Michael','Rose','','2000-05-19','M',4000),
  ('Robert','','Williams','1978-09-05','M',4000),
  ('Maria','Anne','Jones','1967-12-01','F',4000),
  ('Jen','Mary','Brown','1980-02-17','F',-1)
]

columns = ["firstname","middlename","lastname","dob","gender","salary"]
df = spark.createDataFrame(data=data, schema = columns)
print('Original df')
df.show()
print("after concatenating")
df2 = df.select(concat(df.firstname,df.middlename,df.lastname).alias("Fullname"),"dob","gender","salary")
df2.show()

print("after adding the seperators")
df3= df.select(concat_ws('-',df.firstname,df.lastname).alias("column"),"dob","gender","salary")
df3.show()

Original df
+---------+----------+--------+----------+------+------+
|firstname|middlename|lastname|       dob|gender|salary|
+---------+----------+--------+----------+------+------+
|    James|          |   Smith|1991-04-01|     M|  3000|
|  Michael|      Rose|        |2000-05-19|     M|  4000|
|   Robert|          |Williams|1978-09-05|     M|  4000|
|    Maria|      Anne|   Jones|1967-12-01|     F|  4000|
|      Jen|      Mary|   Brown|1980-02-17|     F|    -1|
+---------+----------+--------+----------+------+------+

after concatenating
+--------------+----------+------+------+
|      Fullname|       dob|gender|salary|
+--------------+----------+------+------+
|    JamesSmith|1991-04-01|     M|  3000|
|   MichaelRose|2000-05-19|     M|  4000|
|RobertWilliams|1978-09-05|     M|  4000|
|MariaAnneJones|1967-12-01|     F|  4000|
|  JenMaryBrown|1980-02-17|     F|    -1|
+--------------+----------+------+------+

after adding the seperators
+---------------+----------+------+------+
|         column|       dob|gender|salary|
+---------------+----------+------+------+
|    James-Smith|1991-04-01|     M|  3000|
|       Michael-|2000-05-19|     M|  4000|
|Robert-Williams|1978-09-05|     M|  4000|
|    Maria-Jones|1967-12-01|     F|  4000|
|      Jen-Brown|1980-02-17|     F|    -1|
+---------------+----------+------+------+

In [ ]:
from pyspark.sql.functions import col, initcap, upper, lower, substring, lpad, rpad, ltrim, rtrim
# Sample data
data = [("John Doe",),
        ("Jane Smith",),
        ("Adam Johnson",)]

# Create the DataFrame
df = spark.createDataFrame(data, ["name"])

In [ ]:
#String Functions
print("Output for contains")
df_contains = df.filter(col('name').contains('ohn'))
df_contains.show()
print("Output for startswith")
df_startswith = df.filter(col('name').startswith('J'))
df_startswith.show()
print("Output for endswith")
df_endswith = df.filter(col('name').endswith('Smith'))
df_endswith.show()
print("Output for initcap")
df_initcap = df.select(initcap(df.name).alias('initcap_name'))
df_initcap.show()
print("Output for upper")
df_upper = df.select(upper(df.name).alias('upper_name'))
df_upper.show()
print("Output for lower")
df_lower = df.select(lower(df.name).alias('lower_name'))
df_lower.show()
print("Output for substring")
df_substring = df.select(substring('name', 2, 4).alias('substring_name'))
df_substring.show()
print("Output for lpad")
df_lpad = df.select(lpad('name', 12, 'X').alias('lpad_name'))
df_lpad.show()
print("Output for rpad")
df_rpad = df.select(rpad(df.name, 12, 'Y').alias('rpad_name'))
df_rpad.show()
print("Output for ltrim")
df_ltrim = df.select(ltrim(df.name).alias('ltrim_name'))
df_ltrim.show()
print("Output for rtrim")
df_rtrim = df.select(rtrim(df.name).alias('rtrim_name'))
df_rtrim.show()

Output for contains
+------------+
|        name|
+------------+
|    John Doe|
|Adam Johnson|
+------------+

Output for startswith
+----------+
|      name|
+----------+
|  John Doe|
|Jane Smith|
+----------+

Output for endswith
+----------+
|      name|
+----------+
|Jane Smith|
+----------+

Output for initcap
+------------+
|initcap_name|
+------------+
|    John Doe|
|  Jane Smith|
|Adam Johnson|
+------------+

Output for upper
+------------+
|  upper_name|
+------------+
|    JOHN DOE|
|  JANE SMITH|
|ADAM JOHNSON|
+------------+

Output for lower
+------------+
|  lower_name|
+------------+
|    john doe|
|  jane smith|
|adam johnson|
+------------+

Output for substring
+--------------+
|substring_name|
+--------------+
|          ohn |
|          ane |
|          dam |
+--------------+

Output for lpad
+------------+
|   lpad_name|
+------------+
|XXXXJohn Doe|
|XXJane Smith|
|Adam Johnson|
+------------+

Output for rpad
+------------+
|   rpad_name|
+------------+
|John DoeYYYY|
|Jane SmithYY|
|Adam Johnson|
+------------+

Output for ltrim
+------------+
|  ltrim_name|
+------------+
|    John Doe|
|  Jane Smith|
|Adam Johnson|
+------------+

Output for rtrim
+------------+
|  rtrim_name|
+------------+
|    John Doe|
|  Jane Smith|
|Adam Johnson|
+------------+

In [ ]:
print("DAY 4")

DAY 4

DAY 4

In [ ]:
#SPARK SQL

from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()

data1 = [
    ("1", "Rahul", "Kumar", "Delhi"),
    ("2", "Priya", "Sharma", "Mumbai"),
    ("3", "Amit", "Verma", "Kolkata"),
    ("4", "Sneha", "Gupta", "Chennai"),
    ("5", "Vikram", "Singh", "Bangalore"),
    ("6", "Neha", "Patel", "Hyderabad"),
    ("7", "Rajesh", "Yadav", "Pune"),
    ("8", "Sara", "Malhotra", "Jaipur"),
    ("9", "Rakesh", "Shah", "Ahmedabad"),
    ("10", "Anita", "Rao", "Chandigarh")
]

df1 = spark.createDataFrame(data1, ["id", "first_name", "last_name", "city"])
df1.show()

data2 = [
    ("1", "Rahul", "Kumar", "IT"),
    ("2", "Priya", "Sharma", "Finance"),
    ("3", "Amit", "Verma", "Marketing"),
    ("4", "Sneha", "Gupta", "HR"),
    ("5", "Vikram", "Singh", "IT"),
    ("6", "Neha", "Patel", "Finance"),
    ("7", "Rajesh", "Yadav", "Marketing"),
    ("8", "Sara", "Malhotra", "HR"),
    ("9", "Rakesh", "Shah", "IT"),
    ("10", "Anita", "Rao", "Finance")
]

df2 = spark.createDataFrame(data2, ["id", "first_name", "last_name", "department"])
df2.show()

+---+----------+---------+----------+
| id|first_name|last_name|      city|
+---+----------+---------+----------+
|  1|     Rahul|    Kumar|     Delhi|
|  2|     Priya|   Sharma|    Mumbai|
|  3|      Amit|    Verma|   Kolkata|
|  4|     Sneha|    Gupta|   Chennai|
|  5|    Vikram|    Singh| Bangalore|
|  6|      Neha|    Patel| Hyderabad|
|  7|    Rajesh|    Yadav|      Pune|
|  8|      Sara| Malhotra|    Jaipur|
|  9|    Rakesh|     Shah| Ahmedabad|
| 10|     Anita|      Rao|Chandigarh|
+---+----------+---------+----------+

+---+----------+---------+----------+
| id|first_name|last_name|department|
+---+----------+---------+----------+
|  1|     Rahul|    Kumar|        IT|
|  2|     Priya|   Sharma|   Finance|
|  3|      Amit|    Verma| Marketing|
|  4|     Sneha|    Gupta|        HR|
|  5|    Vikram|    Singh|        IT|
|  6|      Neha|    Patel|   Finance|
|  7|    Rajesh|    Yadav| Marketing|
|  8|      Sara| Malhotra|        HR|
|  9|    Rakesh|     Shah|        IT|
| 10|     Anita|      Rao|   Finance|
+---+----------+---------+----------+

In [ ]:
df1.createOrReplaceTempView("Employess")

In [ ]:
spark.sql("SELECT * FROM Employess").show()

+---+----------+---------+----------+
| id|first_name|last_name|      city|
+---+----------+---------+----------+
|  1|     Rahul|    Kumar|     Delhi|
|  2|     Priya|   Sharma|    Mumbai|
|  3|      Amit|    Verma|   Kolkata|
|  4|     Sneha|    Gupta|   Chennai|
|  5|    Vikram|    Singh| Bangalore|
|  6|      Neha|    Patel| Hyderabad|
|  7|    Rajesh|    Yadav|      Pune|
|  8|      Sara| Malhotra|    Jaipur|
|  9|    Rakesh|     Shah| Ahmedabad|
| 10|     Anita|      Rao|Chandigarh|
+---+----------+---------+----------+

In [ ]:
#where condition
result = spark.sql("SELECT * FROM Employess WHERE city ='Bangalore'")
print('on running SQL Queries with  city =Bangalore condition')
result.show()

on running SQL Queries with  city =Bangalore condition
+---+----------+---------+---------+
| id|first_name|last_name|     city|
+---+----------+---------+---------+
|  5|    Vikram|    Singh|Bangalore|
+---+----------+---------+---------+

In [ ]:
data2 = [
    ("1", "Rahul", "Kumar", "IT","10000"),
    ("2", "Priya", "Sharma", "Finance","20000"),
    ("3", "Amit", "Verma", "Marketing","30000"),
    ("4", "Sneha", "Gupta", "HR","10000"),
    ("5", "Vikram", "Singh", "IT","40000"),
    ("6", "Neha", "Patel", "Finance","50000"),
    ("7", "Rajesh", "Yadav", "Marketing","60000"),
    ("8", "Sara", "Malhotra", "HR","70000"),
    ("9", "Rakesh", "Shah", "IT","80000"),
    ("10", "Anita", "Rao", "Finance","90000")
]

df2 = spark.createDataFrame(data2, ["id", "first_name", "last_name", "Department","Salary"])
df2.show()

+---+----------+---------+----------+------+
| id|first_name|last_name|Department|Salary|
+---+----------+---------+----------+------+
|  1|     Rahul|    Kumar|        IT| 10000|
|  2|     Priya|   Sharma|   Finance| 20000|
|  3|      Amit|    Verma| Marketing| 30000|
|  4|     Sneha|    Gupta|        HR| 10000|
|  5|    Vikram|    Singh|        IT| 40000|
|  6|      Neha|    Patel|   Finance| 50000|
|  7|    Rajesh|    Yadav| Marketing| 60000|
|  8|      Sara| Malhotra|        HR| 70000|
|  9|    Rakesh|     Shah|        IT| 80000|
| 10|     Anita|      Rao|   Finance| 90000|
+---+----------+---------+----------+------+

In [ ]:
df2.createOrReplaceTempView("Employees")
spark.sql("SELECT * FROM Employees").show()

+---+----------+---------+----------+------+
| id|first_name|last_name|Department|Salary|
+---+----------+---------+----------+------+
|  1|     Rahul|    Kumar|        IT| 10000|
|  2|     Priya|   Sharma|   Finance| 20000|
|  3|      Amit|    Verma| Marketing| 30000|
|  4|     Sneha|    Gupta|        HR| 10000|
|  5|    Vikram|    Singh|        IT| 40000|
|  6|      Neha|    Patel|   Finance| 50000|
|  7|    Rajesh|    Yadav| Marketing| 60000|
|  8|      Sara| Malhotra|        HR| 70000|
|  9|    Rakesh|     Shah|        IT| 80000|
| 10|     Anita|      Rao|   Finance| 90000|
+---+----------+---------+----------+------+

In [ ]:
print("After Group By")
result= spark.sql("SELECT Department , Sum(Salary) as Sum_of_Salary FROM Employees GROUP BY Department")
result.show()

After Group By
+----------+-------------+
|Department|Sum_of_Salary|
+----------+-------------+
|        HR|      80000.0|
|   Finance|     160000.0|
| Marketing|      90000.0|
|        IT|     130000.0|
+----------+-------------+

In [ ]:
data1 = [
    ("1", "Rahul", "Kumar", "Delhi"),
    ("2", "Priya", "Sharma", "Mumbai"),
    ("3", "Amit", "Verma", "Kolkata"),
    ("4", "Sneha", "Gupta", "Chennai"),
    ("5", "Vikram", "Singh", "Bangalore"),
    ("6", "Neha", "Patel", "Hyderabad"),
    ("7", "Rajesh", "Yadav", "Pune"),
    ("8", "Sara", "Malhotra", "Jaipur"),
    ("9", "Rakesh", "Shah", "Ahmedabad"),
    ("10", "Anita", "Rao", "Chandigarh")
]

print("DF1(Left Table) -->")
df5 = spark.createDataFrame(data1, ["id", "first_name", "last_name", "city"])
df5.createOrReplaceTempView("left_table")
spark.sql("Select * from left_table").show()

data2 = [
    ("1", "Rahul", "Kumar", "IT"),
    ("2", "Priya", "Sharma", "Finance"),
    ("3", "Amit", "Verma", "Marketing"),
    ("4", "Sneha", "Gupta", "HR"),
    ("5", "Vikram", "Singh", "IT"),
    ("6", "Neha", "Patel", "Finance"),
    ("7", "Rajesh", "Yadav", "Marketing"),
    ("8", "Sara", "Malhotra", "HR"),
    ("9", "Rakesh", "Shah", "IT"),
    ("10", "Anita", "Rao", "Finance")
]

print("DF2(Right Table) -->")
df6 = spark.createDataFrame(data2, ["id", "first_name", "last_name", "department"])
df6.createOrReplaceTempView("right_table")
spark.sql("Select * from right_table").show()

DF1(Left Table) -->
+---+----------+---------+----------+
| id|first_name|last_name|      city|
+---+----------+---------+----------+
|  1|     Rahul|    Kumar|     Delhi|
|  2|     Priya|   Sharma|    Mumbai|
|  3|      Amit|    Verma|   Kolkata|
|  4|     Sneha|    Gupta|   Chennai|
|  5|    Vikram|    Singh| Bangalore|
|  6|      Neha|    Patel| Hyderabad|
|  7|    Rajesh|    Yadav|      Pune|
|  8|      Sara| Malhotra|    Jaipur|
|  9|    Rakesh|     Shah| Ahmedabad|
| 10|     Anita|      Rao|Chandigarh|
+---+----------+---------+----------+

DF2(Right Table) -->
+---+----------+---------+----------+
| id|first_name|last_name|department|
+---+----------+---------+----------+
|  1|     Rahul|    Kumar|        IT|
|  2|     Priya|   Sharma|   Finance|
|  3|      Amit|    Verma| Marketing|
|  4|     Sneha|    Gupta|        HR|
|  5|    Vikram|    Singh|        IT|
|  6|      Neha|    Patel|   Finance|
|  7|    Rajesh|    Yadav| Marketing|
|  8|      Sara| Malhotra|        HR|
|  9|    Rakesh|     Shah|        IT|
| 10|     Anita|      Rao|   Finance|
+---+----------+---------+----------+

In [ ]:
Inner_Join_result = spark.sql("SELECT * FROM left_table lt inner join right_table rt on lt.id = rt.id")
Inner_Join_result.show()

Left_Join_result = spark.sql("SELECT * FROM left_table lt left join right_table rt on lt.id = rt.id")
Left_Join_result.show()

+---+----------+---------+----------+---+----------+---------+----------+
| id|first_name|last_name|      city| id|first_name|last_name|department|
+---+----------+---------+----------+---+----------+---------+----------+
|  1|     Rahul|    Kumar|     Delhi|  1|     Rahul|    Kumar|        IT|
| 10|     Anita|      Rao|Chandigarh| 10|     Anita|      Rao|   Finance|
|  2|     Priya|   Sharma|    Mumbai|  2|     Priya|   Sharma|   Finance|
|  3|      Amit|    Verma|   Kolkata|  3|      Amit|    Verma| Marketing|
|  4|     Sneha|    Gupta|   Chennai|  4|     Sneha|    Gupta|        HR|
|  5|    Vikram|    Singh| Bangalore|  5|    Vikram|    Singh|        IT|
|  6|      Neha|    Patel| Hyderabad|  6|      Neha|    Patel|   Finance|
|  7|    Rajesh|    Yadav|      Pune|  7|    Rajesh|    Yadav| Marketing|
|  8|      Sara| Malhotra|    Jaipur|  8|      Sara| Malhotra|        HR|
|  9|    Rakesh|     Shah| Ahmedabad|  9|    Rakesh|     Shah|        IT|
+---+----------+---------+----------+---+----------+---------+----------+

+---+----------+---------+----------+---+----------+---------+----------+
| id|first_name|last_name|      city| id|first_name|last_name|department|
+---+----------+---------+----------+---+----------+---------+----------+
|  3|      Amit|    Verma|   Kolkata|  3|      Amit|    Verma| Marketing|
|  5|    Vikram|    Singh| Bangalore|  5|    Vikram|    Singh|        IT|
|  1|     Rahul|    Kumar|     Delhi|  1|     Rahul|    Kumar|        IT|
|  4|     Sneha|    Gupta|   Chennai|  4|     Sneha|    Gupta|        HR|
|  2|     Priya|   Sharma|    Mumbai|  2|     Priya|   Sharma|   Finance|
|  7|    Rajesh|    Yadav|      Pune|  7|    Rajesh|    Yadav| Marketing|
|  8|      Sara| Malhotra|    Jaipur|  8|      Sara| Malhotra|        HR|
|  6|      Neha|    Patel| Hyderabad|  6|      Neha|    Patel|   Finance|
|  9|    Rakesh|     Shah| Ahmedabad|  9|    Rakesh|     Shah|        IT|
| 10|     Anita|      Rao|Chandigarh| 10|     Anita|      Rao|   Finance|
+---+----------+---------+----------+---+----------+---------+----------+

In [ ]:
#Connect with Google Drive
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
#Load Existing data
existing_data = spark.read.csv("/content/drive/MyDrive/O2C/Sales invoice Line.csv",header=True, inferSchema=True)
existing_data.show(100)
print('COUNT',existing_data.count())

+------------+--------+----+-------+-------------+-------------+--------------------+--------+-----------+---------------+---------------+--------------------+---------+
|Document No_|Line No_|Type|    No_|Location Code|Shipment Date|         Description|Quantity| Unit Price|Unit Cost (LCY)|Line Discount _|Line Discount Amount|   Amount|
+------------+--------+----+-------+-------------+-------------+--------------------+--------+-----------+---------------+---------------+--------------------+---------+
|      103002|   10000|   3|TIMOTHY|         null|   23-01-2022|Assembling Furnit...|    25.0|     3700.0|           2200|              0|                 0.0|  89725.0|
|      103002|   20000|   3|TIMOTHY|         null|   23-01-2022|Assembling Furnit...|    96.0|     3700.0|           2200|              0|                 0.0| 344544.0|
|      103005|   10000|   2| 1976-W|          RED|   05-01-2022|INNSBRUCK Storage...| 4.37855|    331.091|          10450|              0|                 0.0|   1449.7|
|      103006|   10000|   2| 1976-W|          RED|   05-01-2022|INNSBRUCK Storage...|21.89271|    331.091|          10450|              0|                 0.0|  7248.48|
|      103007|   10000|   2| 1976-W|          RED|   05-01-2022|INNSBRUCK Storage...| 20.6049|    331.091|          10450|             15|             1023.32|  5798.78|
|      103008|   10000|   2| 1976-W|          RED|   05-01-2022|INNSBRUCK Storage...| 20.6049|    331.091|          10450|             15|             1023.32|  5798.78|
|      103009|   10000|   2| 1976-W|          RED|   05-01-2022|INNSBRUCK Storage...|41.20978|    331.091|          10450|             15|             2046.63| 11597.56|
|      103010|   10000|   2| 1976-W|          RED|   05-01-2022|INNSBRUCK Storage...|21.89271|    331.091|          10450|             10|              724.85|  6523.63|
|      103011|   10000|   2|  70000|         null|   05-01-2022|          Side Panel|     3.0|1449.666667|           1090|              0|                 0.0|   4349.0|
|      103012|   10000|   2|  70000|         null|   05-01-2022|          Side Panel|     4.0|   1449.695|           1090|              0|                 0.0|  5798.78|
|      103013|   10000|   2|  70000|         null|   05-01-2022|          Side Panel|     5.0|   1449.696|           1090|              0|                 0.0|  7248.48|
|      103014|   10000|   2|  70000|         null|   05-01-2022|          Side Panel|     1.0|    1232.24|           1090|              0|                 0.0|  1232.24|
|      103015|   10000|   2| 1972-S|          RED|   13-01-2022|MUNICH Swivel Cha...|     6.0|   4666.529|           6670|              0|                 0.0| 27999.17|
|      103015|   20000|   2| 1968-S|          RED|   13-01-2022|MEXICO Swivel Cha...|     4.0|   4666.529|           6670|              0|                 0.0| 18666.12|
|      103015|   30000|   2| 1980-S|          RED|   13-01-2022|MOSCOW Swivel Cha...|     3.0|   4666.529|           6670|              0|                 0.0| 13999.59|
|      103016|   10000|   2| 1920-S|        GREEN|   13-01-2022|ANTWERP Conferenc...|     2.0|    543.258|          22770|              0|                 0.0|  1086.52|
|      103016|   20000|   2| 1900-S|        GREEN|   13-01-2022|PARIS Guest Chair...|     6.0|     161.73|           6770|              0|                 0.0|   970.38|
|      103016|   30000|   2| 1996-S|        GREEN|   13-01-2022|ATLANTA Whiteboar...|     1.0|   1171.754|          49110|              0|                 0.0|  1171.75|
|      103017|   10000|   2| 1896-S|        GREEN|   11-01-2022|         ATHENS Desk|     1.0|    45100.0|          35170|              0|                 0.0|  43747.0|
|      103018|   10000|   2| 1928-S|        GREEN|   15-01-2022|      AMSTERDAM Lamp|     5.0|     2470.0|           1930|              0|                 0.0|  11979.5|
|      103019|   10000|   2| 1968-S|          RED|   09-01-2022|MEXICO Swivel Cha...|     4.0|    159.311|           6670|              0|                 0.0|   637.24|
|      103019|   20000|   2| 1960-S|          RED|   09-01-2022|ROME Guest Chair,...|     7.0|     161.73|           6770|              0|                 0.0|  1132.11|
|      103019|   30000|   2| 1976-W|          RED|   09-01-2022|INNSBRUCK Storage...|     5.0|    331.091|          10450|             10|              165.55|  1489.91|
|      103019|   40000|   2|  70011|          RED|   09-01-2022|          Glass Door|     1.0|     93.428|           2560|             15|               14.01|    79.42|
|      103020|   10000|   2| 1896-S|          RED|   14-01-2022|         ATHENS Desk|     1.0|     839.36|          35170|              0|                 0.0|   839.36|
|      103020|   20000|   2| 1906-S|          RED|   14-01-2022|ATHENS Mobile Ped...|     1.0|    363.661|          15240|              0|                 0.0|   363.66|
|      103021|   10000|   2| 1952-W|        GREEN|   19-01-2022|OSLO Storage Unit...|     1.0|   1914.221|           6500|             15|              287.13|  1627.09|
|      103021|   20000|   2| 1928-W|        GREEN|   19-01-2022|ST.MORITZ Storage...|     1.0|   4130.963|          13330|             15|              619.65|  3511.32|
|      103021|   30000|   2| 1964-W|        GREEN|   19-01-2022|INNSBRUCK Storage...|     1.0|   3525.923|          11890|             15|              528.89|  2997.03|
|      103022|   10000|   2| 1928-S|        GREEN|   21-01-2022|      AMSTERDAM Lamp|    14.0|     56.873|           1930|              0|                 0.0|   796.22|
|      103022|   20000|   2| 1988-W|        GREEN|   21-01-2022|CALGARY Whiteboar...|     1.0|   1558.606|          49210|             10|              155.86|  1402.75|
|      103022|   30000|   2| 1972-S|        GREEN|   21-01-2022|MUNICH Swivel Cha...|     1.0|      197.1|           6670|              0|                 0.0|    197.1|
|      103023|   10000|   2|766BC-C|        GREEN|   16-01-2022|CONTOSO Storage S...|     1.0|    65590.0|          42640|              0|                 0.0|  63622.3|
|      103024|   10000|   2|766BC-A|        GREEN|   20-01-2022|CONTOSO Conferenc...|     2.0|  55320.956|         244350|              0|                 0.0|110641.91|
|      103024|   20000|   0|   null|         null|         null|The conference pa...|     0.0|        0.0|              0|              0|                 0.0|      0.0|
|      103024|   30000|   0|   null|         null|         null|one table, twelve...|     0.0|        0.0|              0|              0|                 0.0|      0.0|
|      103024|   40000|   0|   null|         null|         null| and one whiteboard.|     0.0|        0.0|              0|              0|                 0.0|      0.0|
|      103024|   50000|   2|766BC-C|        GREEN|   20-01-2022|CONTOSO Storage S...|     1.0|   9652.324|          42640|              0|                 0.0|  9652.32|
|      103025|   10000|   2| 1968-W|          RED|   23-01-2022|GRENOBLE Whiteboa...|     2.0| 100218.381|          49210|             15|            30065.51|170371.25|
|      103025|   20000|   2| 1964-W|          RED|   23-01-2022|INNSBRUCK Storage...|     1.0|  30025.539|          11890|             15|             4503.83| 25521.71|
|      103025|   30000|   2| 1960-S|          RED|   23-01-2022|ROME Guest Chair,...|     1.0|  12865.973|           6770|              5|               643.3| 12222.67|
|      103026|   10000|   2| 1992-W|          RED|   18-01-2022|ALBERTVILLE White...|     1.0| 100218.381|          49210|             10|            10021.84| 90196.54|
|  BLSINV/001|   10000|   2| 1968-S|          RED|   05-01-2022|MEXICO Swivel Cha...|     5.0|     8560.0|           6670|              0|                 0.0|  40660.0|
|  BLSINV/001|   20000|   2| 1996-S|          RED|   05-01-2022|ATLANTA Whiteboar...|     7.0|    62960.0|          49110|              0|                 0.0| 418684.0|
|  BLSINV/002|   10000|   3|TIMOTHY|         BLUE|   23-01-2022|Assembling Furnit...|    25.0|     3700.0|           2200|              0|                 0.0|  87875.0|
|  BLSINV/002|   20000|   3|TIMOTHY|         BLUE|   23-01-2022|Assembling Furnit...|   120.0|     3700.0|           2200|              0|                 0.0| 421800.0|
|  BLSINV/003|   10000|   2| 1964-W|         BLUE|   18-01-2022|INNSBRUCK Storage...|    10.0|    20280.0|          11900|              0|                 0.0| 202800.0|
|  BLSINV/003|   20000|   2|  70011|         BLUE|   18-01-2022|          Glass Door|     5.0|     5020.0|           2560|              0|                 0.0|  25100.0|
|  BLSINV/004|   10000|   2| 8908-W|         BLUE|   12-12-2022|Computer - Highli...|     3.0|     7930.0|              0|              0|                 0.0|  23790.0|
|  BLSINV/004|   20000|   2| 8916-W|         BLUE|   12-12-2022|Computer - TURBO ...|     2.0|    12990.0|              0|              0|                 0.0|  25980.0|
|  BLSINV/004|   30000|   2| 8924-W|         BLUE|   12-12-2022|Server - Enterpri...|     1.0|    24040.0|              0|              0|                 0.0|  24040.0|
|  BLSINV/005|   10000|   2| 8916-W|         BLUE|   04-12-2022|Computer - TURBO ...|     1.0|    12990.0|              0|              0|                 0.0|  12990.0|
|  BLSINV/005|   20000|   2| 8924-W|         BLUE|   04-12-2022|Server - Enterpri...|     1.0|    24040.0|              0|              0|                 0.0|  24040.0|
| S-EXP-00001|   10000|   3|TIMOTHY|         null|   23-01-2022|Assembling Furnit...|    25.0|     3700.0|           2200|              0|                 0.0|  92500.0|
| S-EXP-00001|   20000|   3|TIMOTHY|         null|   23-01-2022|Assembling Furnit...|    76.0|     3700.0|           2200|              0|                 0.0| 281200.0|
| S-EXP-00002|   10000|   2| 8908-W|         BLUE|   16-01-2022|Computer - Highli...|     3.0|     7930.0|              0|              0|                 0.0|  23790.0|
| S-EXP-00002|   20000|   2| 8924-W|         BLUE|   16-01-2022|Server - Enterpri...|     1.0|    24040.0|              0|              0|                 0.0|  24040.0|
+------------+--------+----+-------+-------------+-------------+--------------------+--------+-----------+---------------+---------------+--------------------+---------+

COUNT 57

In [ ]:
#Connect with Postgress Database

from pyspark.sql import SparkSession

spark = SparkSession.builder\
    .appName("PostgresSQLExample")\
    .config("spark.jars", "/content/sample_data/postgresql-42.6.0.jar") \
        .getOrCreate()

url = "jdbc:postgresql://localhost:5432/Sample"

properties = {
    "user": "postgres",
    "password": "root"
}

DAY 6

---

### New Section

In [ ]:
#Read Parquet File
parquet_df = spark.read.parquet("/content/drive/MyDrive/practice_file.parquet",header=True, inferSchema=True)
#Show the content of dataframe
parquet_df.show()

+---------+----------+--------+-----+------+------+------------+
|firstname|middlename|lastname|   id|gender|salary|firstnameLen|
+---------+----------+--------+-----+------+------+------------+
|   naveen|          |Williams|42114|     M|  4000|           6|
|    mansi|      Anne|   Jones|39192|     F|  4000|           5|
|   harish|      Mary|   Brown|     |     F|    -1|           6|
+---------+----------+--------+-----+------+------+------------+

In [ ]:
#Read CSV
df_csv = spark.read.csv("/content/drive/MyDrive/O2C/Sales invoice Line.csv",header=True, inferSchema=True)
#Write dataframe to parquet file (overwrite mode)
df_csv.write.mode("overwrite").parquet("/content/drive/MyDrive/O2C/Sales invoice Line.parquet")
#Write dataframe to parquet file (append mode)
df_csv.write.mode("append").parquet("/content/drive/MyDrive/O2C/Sales invoice Line.parquet")
#Write dataframe to parquet file with snappy compression
df_csv.write.mode("overwrite").option("compression", "snappy").parquet("/content/drive/MyDrive/O2C/Sales invoice Line.parquet")

In [ ]:
snappy_write_parquet_df = spark.read.parquet("/content/drive/MyDrive/O2C/Sales invoice Line.parquet",header=True, inferSchema=True)

In [ ]:
#partition() multiple columns
partitiondata_df = df_csv.write.partitionBy("Shipment Date").mode("overwrite").parquet("/content/drive/MyDrive/O2C/Sales invoice Line.parquet")

In [ ]:
from pyspark.sql.window import Window
from pyspark.sql.functions import row_number, rank, dense_rank, min, max, sum, avg, countDistinct,lag,lead

Data = (("Kirti", "Sales", 3000), \
    ("Leo", "Sales", 4600),  \
    ("Neha", "Sales", 4100),   \
    ("Priya", "Finance", 3000),  \
    ("Pooja", "Sales", 3000),    \
    ("Anjali", "Finance", 3300),  \
    ("Kritika", "Finance", 3900),    \
    ("Megha", "Marketing", 3000), \
    ("Megha", "Marketing", 2000),\
    ("Shweta", "Sales", 4100) \
  )

columns= ["employee_name", "department", "salary"]

df = spark.createDataFrame(data = Data, schema = columns)

print("ORIGINAL DF")
df.show()

#Create a window specification
windowspec = Window.partitionBy("department").orderBy("salary")
print("using window function with orderby")
#calcualte row number
#returns sequential number starting from 1 within window partition
print("row number")
df.withColumn("row_number",row_number().over(windowspec)).show()
#calculate rank
print("Rank")
df.withColumn("rank",rank().over(windowspec)).show()
#dense rank
print("Dense Rank")
df.withColumn("dense_rank",dense_rank().over(windowspec)).show()
#Calculate sum
print("SUM COLUMN")
df.withColumn("sum_column",sum("salary").over(windowspec)).show()
#Calculate min
print("MIN COLUMN")
df.withColumn("min_column",min("salary").over(windowspec)).show()
#Calculate max
print("MAX COLUMN")
df.withColumn("max_column",max("salary").over(windowspec)).show()
#Calculate avg
print("AVG COLUMN")
df.withColumn("avg_column",avg("salary").over(windowspec)).show()
#calculate LAG
print("LAG")
df.withColumn("lag",lag("salary",1,default=0).over(windowspec)).show()
#calculate LEAD
print("LEAD")
df.withColumn("lead",lead("salary",1,default=0).over(windowspec)).show()

ORIGINAL DF
+-------------+----------+------+
|employee_name|department|salary|
+-------------+----------+------+
|        Kirti|     Sales|  3000|
|          Leo|     Sales|  4600|
|         Neha|     Sales|  4100|
|        Priya|   Finance|  3000|
|        Pooja|     Sales|  3000|
|       Anjali|   Finance|  3300|
|      Kritika|   Finance|  3900|
|        Megha| Marketing|  3000|
|        Megha| Marketing|  2000|
|       Shweta|     Sales|  4100|
+-------------+----------+------+

using window function with orderby
row number
+-------------+----------+------+----------+
|employee_name|department|salary|row_number|
+-------------+----------+------+----------+
|        Priya|   Finance|  3000|         1|
|       Anjali|   Finance|  3300|         2|
|      Kritika|   Finance|  3900|         3|
|        Megha| Marketing|  2000|         1|
|        Megha| Marketing|  3000|         2|
|        Kirti|     Sales|  3000|         1|
|        Pooja|     Sales|  3000|         2|
|         Neha|     Sales|  4100|         3|
|       Shweta|     Sales|  4100|         4|
|          Leo|     Sales|  4600|         5|
+-------------+----------+------+----------+

Rank
+-------------+----------+------+----+
|employee_name|department|salary|rank|
+-------------+----------+------+----+
|        Priya|   Finance|  3000|   1|
|       Anjali|   Finance|  3300|   2|
|      Kritika|   Finance|  3900|   3|
|        Megha| Marketing|  2000|   1|
|        Megha| Marketing|  3000|   2|
|        Kirti|     Sales|  3000|   1|
|        Pooja|     Sales|  3000|   1|
|         Neha|     Sales|  4100|   3|
|       Shweta|     Sales|  4100|   3|
|          Leo|     Sales|  4600|   5|
+-------------+----------+------+----+

Dense Rank
+-------------+----------+------+----------+
|employee_name|department|salary|dense_rank|
+-------------+----------+------+----------+
|        Priya|   Finance|  3000|         1|
|       Anjali|   Finance|  3300|         2|
|      Kritika|   Finance|  3900|         3|
|        Megha| Marketing|  2000|         1|
|        Megha| Marketing|  3000|         2|
|        Kirti|     Sales|  3000|         1|
|        Pooja|     Sales|  3000|         1|
|         Neha|     Sales|  4100|         2|
|       Shweta|     Sales|  4100|         2|
|          Leo|     Sales|  4600|         3|
+-------------+----------+------+----------+

SUM COLUMN
+-------------+----------+------+----------+
|employee_name|department|salary|sum_column|
+-------------+----------+------+----------+
|        Priya|   Finance|  3000|      3000|
|       Anjali|   Finance|  3300|      6300|
|      Kritika|   Finance|  3900|     10200|
|        Megha| Marketing|  2000|      2000|
|        Megha| Marketing|  3000|      5000|
|        Kirti|     Sales|  3000|      6000|
|        Pooja|     Sales|  3000|      6000|
|         Neha|     Sales|  4100|     14200|
|       Shweta|     Sales|  4100|     14200|
|          Leo|     Sales|  4600|     18800|
+-------------+----------+------+----------+

MIN COLUMN
+-------------+----------+------+----------+
|employee_name|department|salary|min_column|
+-------------+----------+------+----------+
|        Priya|   Finance|  3000|      3000|
|       Anjali|   Finance|  3300|      3000|
|      Kritika|   Finance|  3900|      3000|
|        Megha| Marketing|  2000|      2000|
|        Megha| Marketing|  3000|      2000|
|        Kirti|     Sales|  3000|      3000|
|        Pooja|     Sales|  3000|      3000|
|         Neha|     Sales|  4100|      3000|
|       Shweta|     Sales|  4100|      3000|
|          Leo|     Sales|  4600|      3000|
+-------------+----------+------+----------+

MAX COLUMN
+-------------+----------+------+----------+
|employee_name|department|salary|max_column|
+-------------+----------+------+----------+
|        Priya|   Finance|  3000|      3000|
|       Anjali|   Finance|  3300|      3300|
|      Kritika|   Finance|  3900|      3900|
|        Megha| Marketing|  2000|      2000|
|        Megha| Marketing|  3000|      3000|
|        Kirti|     Sales|  3000|      3000|
|        Pooja|     Sales|  3000|      3000|
|         Neha|     Sales|  4100|      4100|
|       Shweta|     Sales|  4100|      4100|
|          Leo|     Sales|  4600|      4600|
+-------------+----------+------+----------+

AVG COLUMN
+-------------+----------+------+----------+
|employee_name|department|salary|avg_column|
+-------------+----------+------+----------+
|        Priya|   Finance|  3000|    3000.0|
|       Anjali|   Finance|  3300|    3150.0|
|      Kritika|   Finance|  3900|    3400.0|
|        Megha| Marketing|  2000|    2000.0|
|        Megha| Marketing|  3000|    2500.0|
|        Kirti|     Sales|  3000|    3000.0|
|        Pooja|     Sales|  3000|    3000.0|
|         Neha|     Sales|  4100|    3550.0|
|       Shweta|     Sales|  4100|    3550.0|
|          Leo|     Sales|  4600|    3760.0|
+-------------+----------+------+----------+

LAG
+-------------+----------+------+----+
|employee_name|department|salary| lag|
+-------------+----------+------+----+
|        Priya|   Finance|  3000|   0|
|       Anjali|   Finance|  3300|3000|
|      Kritika|   Finance|  3900|3300|
|        Megha| Marketing|  2000|   0|
|        Megha| Marketing|  3000|2000|
|        Kirti|     Sales|  3000|   0|
|        Pooja|     Sales|  3000|3000|
|         Neha|     Sales|  4100|3000|
|       Shweta|     Sales|  4100|4100|
|          Leo|     Sales|  4600|4100|
+-------------+----------+------+----+

LEAD
+-------------+----------+------+----+
|employee_name|department|salary|lead|
+-------------+----------+------+----+
|        Priya|   Finance|  3000|3300|
|       Anjali|   Finance|  3300|3900|
|      Kritika|   Finance|  3900|   0|
|        Megha| Marketing|  2000|3000|
|        Megha| Marketing|  3000|   0|
|        Kirti|     Sales|  3000|3000|
|        Pooja|     Sales|  3000|4100|
|         Neha|     Sales|  4100|4100|
|       Shweta|     Sales|  4100|4600|
|          Leo|     Sales|  4600|   0|
+-------------+----------+------+----+

### DAY 7

In [ ]:
#Connect with SQL DB
from pyspark.sql import SparkSession
spark = SparkSession.builder\
      .appName("MSSQL JDBC Connection")\
      .config("spark.driver.extraClassPath","/content/drive/MyDrive/mssql-jdbc-12.2.0.jre8.jar")\
      .getOrCreate()

## DAY 8 Snapshotting